import calyxo10kFoods from './calyxo10kFoods.json' with { type: 'json' };

// Comprehensive Hand-Curated Indian & International Everyday Staples
export const HAND_CURATED_FOODS = [
  // --- GRAINS, RICE & CEREALS ---
  {
    id: "staple-rice-white",
    name: "Steamed White Rice",
    displayName: "Steamed White Rice (Cooked)",
    category: "Grains & Cereals",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 260,
    protein: 5.4,
    carbs: 56.0,
    fat: 0.6,
    fiber: 0.8,
    sugar: 0.1,
    sodium: 2,
    calsPer100g: 130,
    protPer100g: 2.7,
    carbsPer100g: 28.0,
    fatPer100g: 0.3,
    isStaple: true,
    aliases: ["rice", "white rice", "steamed rice", "boiled rice", "cooked rice", "plain rice", "chawal", "bhaat", "anna", "sadam", "basmati rice", "sona masoori"]
  },
  {
    id: "staple-rice-brown",
    name: "Brown Rice",
    displayName: "Brown Rice (Cooked)",
    category: "Grains & Cereals",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 222,
    protein: 5.2,
    carbs: 46.0,
    fat: 1.8,
    fiber: 3.6,
    sugar: 0.4,
    sodium: 4,
    calsPer100g: 111,
    protPer100g: 2.6,
    carbsPer100g: 23.0,
    fatPer100g: 0.9,
    isStaple: true,
    aliases: ["brown rice", "cooked brown rice", "unpolished rice", "brown chawal", "matta rice"]
  },
  {
    id: "staple-curd-rice",
    name: "Curd Rice",
    displayName: "Curd Rice (Dahi Chawal)",
    category: "Grains & Cereals",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 290,
    protein: 7.0,
    carbs: 40.0,
    fat: 11.0,
    fiber: 1.2,
    sugar: 2.0,
    sodium: 380,
    calsPer100g: 145,
    protPer100g: 3.5,
    carbsPer100g: 20.0,
    fatPer100g: 5.5,
    isStaple: true,
    aliases: ["curd rice", "dahi chawal", "dahi bhaat", "perugu annam", "thayir sadam", "mosaranna", "bagala bath"]
  },
  {
    id: "staple-jeera-rice",
    name: "Jeera Rice",
    displayName: "Jeera Rice (Cumin Rice)",
    category: "Grains & Cereals",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 320,
    protein: 6.0,
    carbs: 54.0,
    fat: 9.0,
    fiber: 1.5,
    sugar: 0.5,
    sodium: 320,
    calsPer100g: 160,
    protPer100g: 3.0,
    carbsPer100g: 27.0,
    fatPer100g: 4.5,
    isStaple: true,
    aliases: ["jeera rice", "zeera rice", "cumin rice", "ghee rice"]
  },
  {
    id: "staple-lemon-rice",
    name: "Lemon Rice",
    displayName: "Lemon Rice (Chitranna)",
    category: "Grains & Cereals",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 350,
    protein: 6.4,
    carbs: 56.0,
    fat: 11.0,
    fiber: 2.0,
    sugar: 1.0,
    sodium: 420,
    calsPer100g: 175,
    protPer100g: 3.2,
    carbsPer100g: 28.0,
    fatPer100g: 5.5,
    isStaple: true,
    aliases: ["lemon rice", "chitranna", "elumichai sadam", "nimmakaya annam"]
  },
  {
    id: "staple-poha",
    name: "Poha",
    displayName: "Poha (Flattened Rice, Cooked)",
    category: "Indian Breakfast",
    servingSize: "150g (1 bowl)",
    pieceWeight: 150,
    unitType: "bowl",
    calories: 195,
    protein: 3.8,
    carbs: 37.5,
    fat: 3.3,
    fiber: 2.2,
    sugar: 1.5,
    sodium: 260,
    calsPer100g: 130,
    protPer100g: 2.5,
    carbsPer100g: 25.0,
    fatPer100g: 2.2,
    isStaple: true,
    aliases: ["poha", "flattened rice", "avalakki", "aval", "chira", "kanda poha", "batata poha"]
  },
  {
    id: "staple-upma",
    name: "Upma",
    displayName: "Rava Upma (Cooked)",
    category: "Indian Breakfast",
    servingSize: "150g (1 bowl)",
    pieceWeight: 150,
    unitType: "bowl",
    calories: 210,
    protein: 5.2,
    carbs: 33.0,
    fat: 6.0,
    fiber: 2.5,
    sugar: 1.0,
    sodium: 290,
    calsPer100g: 140,
    protPer100g: 3.5,
    carbsPer100g: 22.0,
    fatPer100g: 4.0,
    isStaple: true,
    aliases: ["upma", "uppittu", "rava upma", "suji upma", "sooji upma"]
  },
  {
    id: "staple-oats-raw",
    name: "Rolled Oats",
    displayName: "Rolled Oats (Raw / Dry)",
    category: "Fitness & Breakfast",
    servingSize: "40g (approx. 1/2 cup)",
    pieceWeight: 40,
    unitType: "grams",
    calories: 156,
    protein: 6.8,
    carbs: 26.5,
    fat: 2.8,
    fiber: 4.2,
    sugar: 0.4,
    sodium: 2,
    calsPer100g: 389,
    protPer100g: 16.9,
    carbsPer100g: 66.3,
    fatPer100g: 6.9,
    isStaple: true,
    aliases: ["oats", "rolled oats", "quaker oats", "raw oats", "oatmeal dry", "oat flakes"]
  },
  {
    id: "staple-oatmeal-cooked",
    name: "Cooked Oatmeal",
    displayName: "Cooked Oatmeal (in Water/Milk)",
    category: "Fitness & Breakfast",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 142,
    protein: 5.0,
    carbs: 24.0,
    fat: 3.0,
    fiber: 3.5,
    sugar: 1.0,
    sodium: 15,
    calsPer100g: 71,
    protPer100g: 2.5,
    carbsPer100g: 12.0,
    fatPer100g: 1.5,
    isStaple: true,
    aliases: ["oatmeal", "cooked oats", "porridge", "oats porridge", "cooked oatmeal"]
  },

  // --- BREADS & ROTIS ---
  {
    id: "staple-roti",
    name: "Roti",
    displayName: "Roti / Phulka (1 Piece)",
    category: "North Indian Bread",
    servingSize: "35g (1 medium roti)",
    pieceWeight: 35,
    unitType: "piece",
    calories: 92,
    protein: 3.0,
    carbs: 18.2,
    fat: 0.9,
    fiber: 2.3,
    sugar: 0.2,
    sodium: 2,
    calsPer100g: 264,
    protPer100g: 8.5,
    carbsPer100g: 52.0,
    fatPer100g: 2.5,
    isStaple: true,
    aliases: ["roti", "phulka", "fulka", "rotli", "wheat flatbread", "chapati", "chapathi", "atta roti", "whole wheat roti"]
  },
  {
    id: "staple-chapati",
    name: "Chapati",
    displayName: "Chapati (with Light Oil)",
    category: "North Indian Bread",
    servingSize: "40g (1 chapati)",
    pieceWeight: 40,
    unitType: "piece",
    calories: 110,
    protein: 3.3,
    carbs: 20.0,
    fat: 1.8,
    fiber: 2.5,
    sugar: 0.2,
    sodium: 48,
    calsPer100g: 275,
    protPer100g: 8.2,
    carbsPer100g: 50.0,
    fatPer100g: 4.5,
    isStaple: true,
    aliases: ["chapati", "chapathi", "chappati", "oil chapati", "flatbread", "roti"]
  },
  {
    id: "staple-bread-wheat",
    name: "Whole Wheat Bread",
    displayName: "Whole Wheat Bread / Brown Bread (1 Slice)",
    category: "Breads",
    servingSize: "30g (1 slice)",
    pieceWeight: 30,
    unitType: "slice",
    calories: 74,
    protein: 2.7,
    carbs: 13.2,
    fat: 1.1,
    fiber: 1.8,
    sugar: 1.2,
    sodium: 130,
    calsPer100g: 245,
    protPer100g: 9.0,
    carbsPer100g: 44.0,
    fatPer100g: 3.5,
    isStaple: true,
    aliases: ["bread", "brown bread", "whole wheat bread", "wheat bread", "multigrain bread", "toast"]
  },
  {
    id: "staple-bread-white",
    name: "White Bread",
    displayName: "White Bread (1 Slice)",
    category: "Breads",
    servingSize: "28g (1 slice)",
    pieceWeight: 28,
    unitType: "slice",
    calories: 74,
    protein: 2.2,
    carbs: 13.7,
    fat: 0.9,
    fiber: 0.7,
    sugar: 1.5,
    sodium: 140,
    calsPer100g: 265,
    protPer100g: 8.0,
    carbsPer100g: 49.0,
    fatPer100g: 3.2,
    isStaple: true,
    aliases: ["white bread", "sandwich bread", "toast", "sliced bread", "bread"]
  },
  {
    id: "staple-paratha-plain",
    name: "Paratha",
    displayName: "Plain Paratha (1 Piece)",
    category: "North Indian Bread",
    servingSize: "70g (1 medium paratha)",
    pieceWeight: 70,
    unitType: "piece",
    calories: 224,
    protein: 4.6,
    carbs: 31.5,
    fat: 9.1,
    fiber: 2.8,
    sugar: 0.5,
    sodium: 180,
    calsPer100g: 320,
    protPer100g: 6.5,
    carbsPer100g: 45.0,
    fatPer100g: 13.0,
    isStaple: true,
    aliases: ["paratha", "plain paratha", "parotha", "layered paratha", "tawa paratha"]
  },
  {
    id: "staple-paratha-aloo",
    name: "Aloo Paratha",
    displayName: "Aloo Paratha (Stuffed Potato)",
    category: "North Indian Bread",
    servingSize: "120g (1 large paratha)",
    pieceWeight: 120,
    unitType: "piece",
    calories: 276,
    protein: 6.0,
    carbs: 42.0,
    fat: 9.6,
    fiber: 3.6,
    sugar: 1.2,
    sodium: 340,
    calsPer100g: 230,
    protPer100g: 5.0,
    carbsPer100g: 35.0,
    fatPer100g: 8.0,
    isStaple: true,
    aliases: ["aloo paratha", "potato paratha", "stuffed paratha", "alu paratha"]
  },
  {
    id: "staple-naan",
    name: "Butter Naan",
    displayName: "Butter Naan (1 Piece)",
    category: "North Indian Bread",
    servingSize: "100g (1 piece)",
    pieceWeight: 100,
    unitType: "piece",
    calories: 310,
    protein: 8.5,
    carbs: 50.0,
    fat: 8.5,
    fiber: 2.0,
    sugar: 2.5,
    sodium: 450,
    calsPer100g: 310,
    protPer100g: 8.5,
    carbsPer100g: 50.0,
    fatPer100g: 8.5,
    isStaple: true,
    aliases: ["naan", "butter naan", "garlic naan", "tandoori naan", "plain naan"]
  },

  // --- SOUTH INDIAN STAPLES ---
  {
    id: "staple-idli",
    name: "Idli",
    displayName: "Steamed Idli (1 Piece)",
    category: "South Indian Breakfast",
    servingSize: "50g (1 idli)",
    pieceWeight: 50,
    unitType: "piece",
    calories: 66,
    protein: 2.3,
    carbs: 13.3,
    fat: 0.3,
    fiber: 0.9,
    sugar: 0.1,
    sodium: 110,
    calsPer100g: 132,
    protPer100g: 4.5,
    carbsPer100g: 26.5,
    fatPer100g: 0.6,
    isStaple: true,
    aliases: ["idli", "idly", "steamed rice cake", "thatte idli", "rava idli"]
  },
  {
    id: "staple-dosa-plain",
    name: "Plain Dosa",
    displayName: "Plain Dosa (1 Large)",
    category: "South Indian Breakfast",
    servingSize: "100g (1 dosa)",
    pieceWeight: 100,
    unitType: "piece",
    calories: 168,
    protein: 3.8,
    carbs: 29.0,
    fat: 3.7,
    fiber: 1.8,
    sugar: 0.5,
    sodium: 240,
    calsPer100g: 168,
    protPer100g: 3.8,
    carbsPer100g: 29.0,
    fatPer100g: 3.7,
    isStaple: true,
    aliases: ["dosa", "plain dosa", "sada dosa", "dosai", "crispy dosa", "ghee roast"]
  },
  {
    id: "staple-dosa-masala",
    name: "Masala Dosa",
    displayName: "Masala Dosa (with Potato Filling)",
    category: "South Indian Breakfast",
    servingSize: "150g (1 large dosa)",
    pieceWeight: 150,
    unitType: "piece",
    calories: 312,
    protein: 6.2,
    carbs: 52.5,
    fat: 8.7,
    fiber: 3.5,
    sugar: 1.2,
    sodium: 480,
    calsPer100g: 208,
    protPer100g: 4.1,
    carbsPer100g: 35.0,
    fatPer100g: 5.8,
    isStaple: true,
    aliases: ["masala dosa", "aloo dosa", "masala dosai", "crispy masala dosa", "mysore masala dosa", "dosa"]
  },
  {
    id: "staple-vada",
    name: "Medu Vada",
    displayName: "Medu Vada (1 Piece)",
    category: "South Indian Breakfast",
    servingSize: "50g (1 vada)",
    pieceWeight: 50,
    unitType: "piece",
    calories: 135,
    protein: 4.3,
    carbs: 12.5,
    fat: 7.8,
    fiber: 1.8,
    sugar: 0.2,
    sodium: 210,
    calsPer100g: 270,
    protPer100g: 8.5,
    carbsPer100g: 25.0,
    fatPer100g: 15.5,
    isStaple: true,
    aliases: ["vada", "medu vada", "uddina vada", "vadai", "sambar vada"]
  },
  {
    id: "staple-sambar",
    name: "Sambar",
    displayName: "South Indian Sambar (1 Bowl)",
    category: "South Indian Soup & Curry",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 130,
    protein: 6.4,
    carbs: 20.0,
    fat: 3.0,
    fiber: 4.5,
    sugar: 2.5,
    sodium: 480,
    calsPer100g: 65,
    protPer100g: 3.2,
    carbsPer100g: 10.0,
    fatPer100g: 1.5,
    isStaple: true,
    aliases: ["sambar", "sambhar", "south indian sambar", "lentil soup", "paruppu sambar"]
  },

  // --- EGGS & POULTRY / MEAT ---
  {
    id: "staple-egg-boiled",
    name: "Whole Boiled Egg",
    displayName: "Whole Boiled Egg (1 Large)",
    category: "Eggs & Poultry",
    servingSize: "50g (1 large egg)",
    pieceWeight: 50,
    unitType: "piece",
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    sugar: 0.3,
    sodium: 62,
    calsPer100g: 155,
    protPer100g: 12.6,
    carbsPer100g: 1.1,
    fatPer100g: 10.6,
    isStaple: true,
    aliases: ["egg", "eggs", "boiled egg", "whole egg", "hard boiled egg", "anda", "ubla anda", "motte", "muttai", "egg whole"]
  },
  {
    id: "staple-egg-white",
    name: "Egg White",
    displayName: "Egg White (Boiled / Cooked)",
    category: "Eggs & Poultry",
    servingSize: "33g (1 egg white)",
    pieceWeight: 33,
    unitType: "piece",
    calories: 17,
    protein: 3.6,
    carbs: 0.2,
    fat: 0.1,
    fiber: 0,
    sugar: 0.2,
    sodium: 55,
    calsPer100g: 52,
    protPer100g: 11.0,
    carbsPer100g: 0.7,
    fatPer100g: 0.2,
    isStaple: true,
    aliases: ["egg white", "egg whites", "ande ki safedi", "egg album", "egg white cooked"]
  },
  {
    id: "staple-egg-scrambled",
    name: "Scrambled Eggs",
    displayName: "Scrambled Eggs (Egg Bhurji)",
    category: "Eggs & Poultry",
    servingSize: "100g (approx. 2 eggs)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 148,
    protein: 10.0,
    carbs: 1.5,
    fat: 11.0,
    fiber: 0.2,
    sugar: 0.5,
    sodium: 220,
    calsPer100g: 148,
    protPer100g: 10.0,
    carbsPer100g: 1.5,
    fatPer100g: 11.0,
    isStaple: true,
    aliases: ["scrambled eggs", "egg bhurji", "anda bhurji", "ande ki bhurji", "scrambled egg", "egg"]
  },
  {
    id: "staple-omelette",
    name: "Omelette",
    displayName: "Egg Omelette (Plain / 2 Eggs)",
    category: "Eggs & Poultry",
    servingSize: "100g (1 omelette)",
    pieceWeight: 100,
    unitType: "piece",
    calories: 154,
    protein: 11.0,
    carbs: 1.0,
    fat: 12.0,
    fiber: 0.3,
    sugar: 0.4,
    sodium: 240,
    calsPer100g: 154,
    protPer100g: 11.0,
    carbsPer100g: 1.0,
    fatPer100g: 12.0,
    isStaple: true,
    aliases: ["omelette", "omelet", "egg omelette", "masala omelette", "anda omelette", "egg"]
  },
  {
    id: "staple-chicken-breast",
    name: "Grilled Chicken Breast",
    displayName: "Grilled Chicken Breast (Cooked, Boneless)",
    category: "Meat & Poultry",
    servingSize: "100g (1 portion)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    calsPer100g: 165,
    protPer100g: 31.0,
    carbsPer100g: 0.0,
    fatPer100g: 3.6,
    isStaple: true,
    aliases: ["chicken breast", "grilled chicken", "cooked chicken breast", "boneless chicken breast", "roasted chicken breast", "chicken"]
  },
  {
    id: "staple-chicken-raw",
    name: "Raw Chicken Breast",
    displayName: "Raw Chicken Breast (Boneless)",
    category: "Meat & Poultry",
    servingSize: "100g (raw weight)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 120,
    protein: 22.5,
    carbs: 0.0,
    fat: 2.6,
    fiber: 0,
    sugar: 0,
    sodium: 65,
    calsPer100g: 120,
    protPer100g: 22.5,
    carbsPer100g: 0.0,
    fatPer100g: 2.6,
    isStaple: true,
    aliases: ["raw chicken", "raw chicken breast", "boneless chicken raw", "chicken raw"]
  },
  {
    id: "staple-chicken-biryani",
    name: "Chicken Biryani",
    displayName: "Chicken Biryani (1 Bowl)",
    category: "Indian Rice & Main Course",
    servingSize: "250g (1 bowl)",
    pieceWeight: 250,
    unitType: "bowl",
    calories: 350,
    protein: 23.3,
    carbs: 40.0,
    fat: 11.5,
    fiber: 2.0,
    sugar: 1.0,
    sodium: 520,
    calsPer100g: 140,
    protPer100g: 9.3,
    carbsPer100g: 16.0,
    fatPer100g: 4.6,
    isStaple: true,
    aliases: ["chicken biryani", "biryani", "dum biryani", "hyderabadi biryani", "murgh biryani"]
  },
  {
    id: "staple-chicken-curry",
    name: "Chicken Curry",
    displayName: "Chicken Curry (Home-style)",
    category: "Meat & Poultry",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 290,
    protein: 29.0,
    carbs: 8.0,
    fat: 16.0,
    fiber: 2.0,
    sugar: 1.5,
    sodium: 560,
    calsPer100g: 145,
    protPer100g: 14.5,
    carbsPer100g: 4.0,
    fatPer100g: 8.0,
    isStaple: true,
    aliases: ["chicken curry", "chicken gravy", "tari wala chicken", "kozhi curry", "kodi kura", "chicken"]
  },
  {
    id: "staple-tandoori-chicken",
    name: "Tandoori Chicken",
    displayName: "Tandoori Chicken (Grilled)",
    category: "Meat & Poultry",
    servingSize: "150g (1 leg/breast piece)",
    pieceWeight: 150,
    unitType: "piece",
    calories: 292,
    protein: 36.0,
    carbs: 5.2,
    fat: 14.2,
    fiber: 1.0,
    sugar: 1.0,
    sodium: 620,
    calsPer100g: 195,
    protPer100g: 24.0,
    carbsPer100g: 3.5,
    fatPer100g: 9.5,
    isStaple: true,
    aliases: ["tandoori chicken", "chicken tikka", "grilled chicken kebab", "roasted chicken"]
  },
  {
    id: "staple-salmon",
    name: "Grilled Salmon",
    displayName: "Grilled Salmon Fillet",
    category: "Fish & Seafood",
    servingSize: "150g (1 fillet)",
    pieceWeight: 150,
    unitType: "grams",
    calories: 309,
    protein: 33.0,
    carbs: 0.0,
    fat: 18.8,
    fiber: 0,
    sugar: 0,
    sodium: 85,
    calsPer100g: 206,
    protPer100g: 22.0,
    carbsPer100g: 0.0,
    fatPer100g: 12.5,
    isStaple: true,
    aliases: ["salmon", "grilled salmon", "fish fillet", "baked fish", "fish"]
  },
  {
    id: "staple-tuna",
    name: "Canned Tuna",
    displayName: "Canned Tuna (in Water/Brine)",
    category: "Fish & Seafood",
    servingSize: "100g (drained weight)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 116,
    protein: 26.0,
    carbs: 0.0,
    fat: 1.0,
    fiber: 0,
    sugar: 0,
    sodium: 320,
    calsPer100g: 116,
    protPer100g: 26.0,
    carbsPer100g: 0.0,
    fatPer100g: 1.0,
    isStaple: true,
    aliases: ["tuna", "canned tuna", "tuna fish", "tuna chunks", "fish"]
  },

  // --- DAIRY & VEGETARIAN PROTEIN ---
  {
    id: "staple-paneer-raw",
    name: "Paneer",
    displayName: "Raw Paneer / Cottage Cheese",
    category: "Dairy & Protein",
    servingSize: "100g (1 portion)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 265,
    protein: 18.3,
    carbs: 3.5,
    fat: 20.8,
    fiber: 0,
    sugar: 2.0,
    sodium: 25,
    calsPer100g: 265,
    protPer100g: 18.3,
    carbsPer100g: 3.5,
    fatPer100g: 20.8,
    isStaple: true,
    aliases: ["paneer", "fresh paneer", "cottage cheese", "raw paneer", "paneer cubes"]
  },
  {
    id: "staple-paneer-lowfat",
    name: "Low-Fat Paneer",
    displayName: "Low-Fat / Diet Paneer",
    category: "Dairy & Protein",
    servingSize: "100g (1 portion)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 180,
    protein: 24.0,
    carbs: 4.0,
    fat: 7.5,
    fiber: 0,
    sugar: 2.5,
    sodium: 30,
    calsPer100g: 180,
    protPer100g: 24.0,
    carbsPer100g: 4.0,
    fatPer100g: 7.5,
    isStaple: true,
    aliases: ["low fat paneer", "skim paneer", "diet paneer", "protein paneer", "paneer"]
  },
  {
    id: "staple-paneer-tikka",
    name: "Paneer Tikka",
    displayName: "Paneer Tikka (Grilled)",
    category: "Dairy & Protein",
    servingSize: "150g (4-5 cubes)",
    pieceWeight: 150,
    unitType: "grams",
    calories: 345,
    protein: 22.5,
    carbs: 9.0,
    fat: 24.0,
    fiber: 1.5,
    sugar: 2.0,
    sodium: 480,
    calsPer100g: 230,
    protPer100g: 15.0,
    carbsPer100g: 6.0,
    fatPer100g: 16.0,
    isStaple: true,
    aliases: ["paneer tikka", "grilled paneer", "tandoori paneer", "paneer"]
  },
  {
    id: "staple-paneer-butter-masala",
    name: "Paneer Butter Masala",
    displayName: "Paneer Butter Masala (1 Bowl)",
    category: "North Indian Curry",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 360,
    protein: 14.0,
    carbs: 12.0,
    fat: 28.0,
    fiber: 2.5,
    sugar: 4.0,
    sodium: 620,
    calsPer100g: 180,
    protPer100g: 7.0,
    carbsPer100g: 6.0,
    fatPer100g: 14.0,
    isStaple: true,
    aliases: ["paneer butter masala", "paneer makhani", "shahi paneer", "paneer curry", "paneer gravy", "paneer"]
  },
  {
    id: "staple-milk-whole",
    name: "Whole Milk",
    displayName: "Whole Milk / Cow's Milk (1 Cup)",
    category: "Dairy",
    servingSize: "240ml (1 cup)",
    pieceWeight: 240,
    unitType: "cup",
    calories: 149,
    protein: 7.7,
    carbs: 11.5,
    fat: 8.4,
    fiber: 0,
    sugar: 11.5,
    sodium: 105,
    calsPer100g: 62,
    protPer100g: 3.2,
    carbsPer100g: 4.8,
    fatPer100g: 3.5,
    isStaple: true,
    aliases: ["milk", "cow milk", "whole milk", "doodh", "haalu", "paal", "dairy milk"]
  },
  {
    id: "staple-milk-toned",
    name: "Toned Milk",
    displayName: "Toned / Skim Milk (1 Cup)",
    category: "Dairy",
    servingSize: "240ml (1 cup)",
    pieceWeight: 240,
    unitType: "cup",
    calories: 101,
    protein: 8.2,
    carbs: 12.0,
    fat: 1.2,
    fiber: 0,
    sugar: 12.0,
    sodium: 115,
    calsPer100g: 42,
    protPer100g: 3.4,
    carbsPer100g: 5.0,
    fatPer100g: 0.5,
    isStaple: true,
    aliases: ["skim milk", "toned milk", "low fat milk", "double toned milk", "milk"]
  },
  {
    id: "staple-curd-plain",
    name: "Plain Curd",
    displayName: "Plain Curd / Dahi / Yogurt (1 Cup)",
    category: "Dairy",
    servingSize: "150g (1 cup / small bowl)",
    pieceWeight: 150,
    unitType: "cup",
    calories: 92,
    protein: 5.3,
    carbs: 7.0,
    fat: 5.0,
    fiber: 0,
    sugar: 7.0,
    sodium: 70,
    calsPer100g: 61,
    protPer100g: 3.5,
    carbsPer100g: 4.7,
    fatPer100g: 3.3,
    isStaple: true,
    aliases: ["curd", "dahi", "yogurt", "plain curd", "mosaru", "thayir", "homemade curd", "perugu"]
  },
  {
    id: "staple-greek-yogurt",
    name: "Greek Yogurt",
    displayName: "Plain Greek Yogurt (High Protein)",
    category: "Dairy & Fitness",
    servingSize: "150g (1 cup)",
    pieceWeight: 150,
    unitType: "cup",
    calories: 110,
    protein: 15.0,
    carbs: 6.0,
    fat: 2.2,
    fiber: 0,
    sugar: 5.0,
    sodium: 55,
    calsPer100g: 73,
    protPer100g: 10.0,
    carbsPer100g: 4.0,
    fatPer100g: 1.5,
    isStaple: true,
    aliases: ["greek yogurt", "hung curd", "protein curd", "high protein yogurt", "curd", "yogurt", "epigamia"]
  },
  {
    id: "staple-tofu",
    name: "Tofu",
    displayName: "Firm Tofu / Soy Paneer",
    category: "Vegan Protein",
    servingSize: "100g (1 portion)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 83,
    protein: 10.0,
    carbs: 2.0,
    fat: 4.5,
    fiber: 1.0,
    sugar: 0.5,
    sodium: 10,
    calsPer100g: 83,
    protPer100g: 10.0,
    carbsPer100g: 2.0,
    fatPer100g: 4.5,
    isStaple: true,
    aliases: ["tofu", "soy paneer", "firm tofu", "bean curd", "soya paneer"]
  },
  {
    id: "staple-soya-chunks",
    name: "Soya Chunks",
    displayName: "Cooked Soya Chunks (Mealmaker)",
    category: "Vegan Protein",
    servingSize: "100g (cooked)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 110,
    protein: 17.5,
    carbs: 8.0,
    fat: 0.5,
    fiber: 4.0,
    sugar: 1.0,
    sodium: 20,
    calsPer100g: 110,
    protPer100g: 17.5,
    carbsPer100g: 8.0,
    fatPer100g: 0.5,
    isStaple: true,
    aliases: ["soya chunks", "mealmaker", "nutrela", "soya nuggets", "soy chunks", "soya"]
  },

  // --- DALS & LEGUMES ---
  {
    id: "staple-dal-tadka",
    name: "Dal Tadka",
    displayName: "Dal Tadka / Yellow Dal (1 Bowl)",
    category: "Indian Curry & Lentils",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 220,
    protein: 12.0,
    carbs: 30.0,
    fat: 6.0,
    fiber: 8.0,
    sugar: 1.5,
    sodium: 490,
    calsPer100g: 110,
    protPer100g: 6.0,
    carbsPer100g: 15.0,
    fatPer100g: 3.0,
    isStaple: true,
    aliases: ["dal tadka", "yellow dal", "toor dal", "arhar dal", "dal fry", "dal", "daal", "paruppu", "bele saaru"]
  },
  {
    id: "staple-dal-makhani",
    name: "Dal Makhani",
    displayName: "Dal Makhani (Black Dal, 1 Bowl)",
    category: "Indian Curry & Lentils",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 270,
    protein: 10.0,
    carbs: 28.0,
    fat: 14.0,
    fiber: 7.0,
    sugar: 2.0,
    sodium: 540,
    calsPer100g: 135,
    protPer100g: 5.0,
    carbsPer100g: 14.0,
    fatPer100g: 7.0,
    isStaple: true,
    aliases: ["dal makhani", "urad dal", "black dal", "maa ki dal", "dal"]
  },
  {
    id: "staple-chole",
    name: "Chole",
    displayName: "Chole / Chana Masala (1 Bowl)",
    category: "Indian Curry & Lentils",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 280,
    protein: 13.0,
    carbs: 36.0,
    fat: 9.0,
    fiber: 9.0,
    sugar: 3.0,
    sodium: 520,
    calsPer100g: 140,
    protPer100g: 6.5,
    carbsPer100g: 18.0,
    fatPer100g: 4.5,
    isStaple: true,
    aliases: ["chole", "chana masala", "chickpeas curry", "kabuli chana", "chana"]
  },
  {
    id: "staple-rajma",
    name: "Rajma",
    displayName: "Rajma / Kidney Beans Curry (1 Bowl)",
    category: "Indian Curry & Lentils",
    servingSize: "200g (1 bowl)",
    pieceWeight: 200,
    unitType: "bowl",
    calories: 260,
    protein: 12.0,
    carbs: 38.0,
    fat: 7.0,
    fiber: 10.0,
    sugar: 2.5,
    sodium: 490,
    calsPer100g: 130,
    protPer100g: 6.0,
    carbsPer100g: 19.0,
    fatPer100g: 3.5,
    isStaple: true,
    aliases: ["rajma", "kidney beans", "rajma chawal", "rajma curry"]
  },
  {
    id: "staple-boiled-chana",
    name: "Boiled Chickpeas",
    displayName: "Boiled Chickpeas / Chana",
    category: "Indian Curry & Lentils",
    servingSize: "100g (1 portion)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 164,
    protein: 8.9,
    carbs: 27.4,
    fat: 2.6,
    fiber: 7.6,
    sugar: 4.8,
    sodium: 24,
    calsPer100g: 164,
    protPer100g: 8.9,
    carbsPer100g: 27.4,
    fatPer100g: 2.6,
    isStaple: true,
    aliases: ["boiled chickpeas", "boiled chana", "boiled garbanzo", "white chana boiled", "kala chana boiled"]
  },

  // --- FITNESS SUPPLEMENTS & HEALTHY FATS ---
  {
    id: "staple-whey-protein",
    name: "Whey Protein Powder",
    displayName: "Whey Protein Powder (1 Scoop)",
    category: "Supplements & Fitness",
    servingSize: "30g (1 scoop)",
    pieceWeight: 30,
    unitType: "scoop",
    calories: 117,
    protein: 23.4,
    carbs: 2.4,
    fat: 1.2,
    fiber: 0,
    sugar: 0.8,
    sodium: 50,
    calsPer100g: 390,
    protPer100g: 78.0,
    carbsPer100g: 8.0,
    fatPer100g: 4.0,
    isStaple: true,
    aliases: ["protein", "whey protein", "protein powder", "protein shake", "whey", "isolate", "gold standard", "whey isolate", "muscleblaze", "myprotein"]
  },
  {
    id: "staple-plant-protein",
    name: "Plant Protein Powder",
    displayName: "Plant / Pea Protein Powder (1 Scoop)",
    category: "Supplements & Fitness",
    servingSize: "33g (1 scoop)",
    pieceWeight: 33,
    unitType: "scoop",
    calories: 124,
    protein: 23.8,
    carbs: 3.0,
    fat: 1.7,
    fiber: 1.5,
    sugar: 0.5,
    sodium: 180,
    calsPer100g: 375,
    protPer100g: 72.0,
    carbsPer100g: 9.0,
    fatPer100g: 5.0,
    isStaple: true,
    aliases: ["plant protein", "vegan protein", "pea protein", "cosmix", "plix", "protein powder"]
  },
  {
    id: "staple-peanut-butter",
    name: "Peanut Butter",
    displayName: "Peanut Butter (1 Tablespoon)",
    category: "Healthy Fats & Spreads",
    servingSize: "16g (1 tbsp)",
    pieceWeight: 16,
    unitType: "tbsp",
    calories: 94,
    protein: 4.0,
    carbs: 3.2,
    fat: 8.0,
    fiber: 1.0,
    sugar: 1.5,
    sodium: 70,
    calsPer100g: 588,
    protPer100g: 25.0,
    carbsPer100g: 20.0,
    fatPer100g: 50.0,
    isStaple: true,
    aliases: ["peanut butter", "pintola", "myfitness", "crunchy peanut butter", "creamy peanut butter", "pb"]
  },
  {
    id: "staple-almonds",
    name: "Almonds",
    displayName: "Raw Almonds / Badam (1 Handful / 28g)",
    category: "Nuts & Seeds",
    servingSize: "28g (approx. 20-24 nuts)",
    pieceWeight: 28,
    unitType: "grams",
    calories: 162,
    protein: 5.9,
    carbs: 6.0,
    fat: 14.0,
    fiber: 3.5,
    sugar: 1.2,
    sodium: 1,
    calsPer100g: 579,
    protPer100g: 21.2,
    carbsPer100g: 21.6,
    fatPer100g: 49.9,
    isStaple: true,
    aliases: ["almonds", "badam", "raw almonds", "roasted almonds", "nuts"]
  },
  {
    id: "staple-walnuts",
    name: "Walnuts",
    displayName: "Walnuts / Akhrot (28g)",
    category: "Nuts & Seeds",
    servingSize: "28g (approx. 7 whole halves)",
    pieceWeight: 28,
    unitType: "grams",
    calories: 183,
    protein: 4.3,
    carbs: 3.8,
    fat: 18.3,
    fiber: 1.9,
    sugar: 0.7,
    sodium: 1,
    calsPer100g: 654,
    protPer100g: 15.2,
    carbsPer100g: 13.7,
    fatPer100g: 65.2,
    isStaple: true,
    aliases: ["walnuts", "akhrot", "raw walnuts", "nuts"]
  },
  {
    id: "staple-ghee",
    name: "Ghee",
    displayName: "Desi Ghee (1 Teaspoon)",
    category: "Fats & Oils",
    servingSize: "5g (1 tsp)",
    pieceWeight: 5,
    unitType: "tsp",
    calories: 45,
    protein: 0.0,
    carbs: 0.0,
    fat: 5.0,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    calsPer100g: 900,
    protPer100g: 0.0,
    carbsPer100g: 0.0,
    fatPer100g: 100.0,
    isStaple: true,
    aliases: ["ghee", "desi ghee", "clarified butter", "tuppa", "nei", "butter"]
  },
  {
    id: "staple-olive-oil",
    name: "Olive Oil",
    displayName: "Olive Oil / Cooking Oil (1 Tbsp)",
    category: "Fats & Oils",
    servingSize: "14g (1 tbsp)",
    pieceWeight: 14,
    unitType: "tbsp",
    calories: 124,
    protein: 0.0,
    carbs: 0.0,
    fat: 14.0,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    calsPer100g: 884,
    protPer100g: 0.0,
    carbsPer100g: 0.0,
    fatPer100g: 100.0,
    isStaple: true,
    aliases: ["olive oil", "cooking oil", "mustard oil", "sunflower oil", "oil"]
  },

  // --- FRUITS & VEGETABLES ---
  {
    id: "staple-banana",
    name: "Banana",
    displayName: "Fresh Banana (1 Medium)",
    category: "Fruits",
    servingSize: "118g (1 medium banana)",
    pieceWeight: 118,
    unitType: "piece",
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.4,
    fiber: 3.1,
    sugar: 14.4,
    sodium: 1,
    calsPer100g: 89,
    protPer100g: 1.1,
    carbsPer100g: 22.8,
    fatPer100g: 0.3,
    isStaple: true,
    aliases: ["banana", "fresh banana", "yellow banana", "kela", "baalehannu", "pazham", "fruit"]
  },
  {
    id: "staple-apple",
    name: "Apple",
    displayName: "Fresh Apple (1 Medium)",
    category: "Fruits",
    servingSize: "180g (1 medium apple)",
    pieceWeight: 180,
    unitType: "piece",
    calories: 94,
    protein: 0.5,
    carbs: 25.0,
    fat: 0.4,
    fiber: 4.4,
    sugar: 19.0,
    sodium: 2,
    calsPer100g: 52,
    protPer100g: 0.3,
    carbsPer100g: 13.8,
    fatPer100g: 0.2,
    isStaple: true,
    aliases: ["apple", "fresh apple", "red apple", "seb", "apple fruit", "fruit"]
  },
  {
    id: "staple-potato-boiled",
    name: "Boiled Potato",
    displayName: "Boiled Potato / Aloo",
    category: "Vegetables",
    servingSize: "100g (1 medium potato)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 87,
    protein: 1.9,
    carbs: 20.1,
    fat: 0.1,
    fiber: 1.8,
    sugar: 0.8,
    sodium: 6,
    calsPer100g: 87,
    protPer100g: 1.9,
    carbsPer100g: 20.1,
    fatPer100g: 0.1,
    isStaple: true,
    aliases: ["potato", "boiled potato", "aloo", "alu", "batata", "potatoes"]
  },
  {
    id: "staple-sweet-potato",
    name: "Sweet Potato",
    displayName: "Boiled Sweet Potato (Shakarkandi)",
    category: "Vegetables",
    servingSize: "100g (1 portion)",
    pieceWeight: 100,
    unitType: "grams",
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3.0,
    sugar: 4.2,
    sodium: 55,
    calsPer100g: 86,
    protPer100g: 1.6,
    carbsPer100g: 20.1,
    fatPer100g: 0.1,
    isStaple: true,
    aliases: ["sweet potato", "shakarkandi", "sweet aloo", "boiled sweet potato"]
  },
  {
    id: "staple-tea",
    name: "Indian Chai",
    displayName: "Indian Chai / Tea (with Milk)",
    category: "Beverages",
    servingSize: "150ml (1 cup)",
    pieceWeight: 150,
    unitType: "cup",
    calories: 98,
    protein: 3.0,
    carbs: 13.5,
    fat: 3.8,
    fiber: 0,
    sugar: 10.0,
    sodium: 45,
    calsPer100g: 65,
    protPer100g: 2.0,
    carbsPer100g: 9.0,
    fatPer100g: 2.5,
    isStaple: true,
    aliases: ["chai", "tea", "milk tea", "indian chai", "masala chai", "chaha"]
  },
  {
    id: "staple-coffee-black",
    name: "Black Coffee",
    displayName: "Black Coffee (No Sugar)",
    category: "Beverages",
    servingSize: "200ml (1 cup)",
    pieceWeight: 200,
    unitType: "cup",
    calories: 4,
    protein: 0.6,
    carbs: 0.0,
    fat: 0.0,
    fiber: 0,
    sugar: 0,
    sodium: 5,
    calsPer100g: 2,
    protPer100g: 0.3,
    carbsPer100g: 0.0,
    fatPer100g: 0.0,
    isStaple: true,
    aliases: ["black coffee", "coffee", "espresso", "americano", "filter coffee no sugar"]
  }
];

// Quick Access Staples for Fast 1-Tap Logging
export const POPULAR_STAPLES = [
  HAND_CURATED_FOODS[0], // Steamed White Rice
  HAND_CURATED_FOODS[9], // Roti / Phulka
  HAND_CURATED_FOODS[16], // Whole Boiled Egg
  HAND_CURATED_FOODS[20], // Grilled Chicken Breast
  HAND_CURATED_FOODS[14], // Plain Dosa
  HAND_CURATED_FOODS[7],  // Rolled Oats
  HAND_CURATED_FOODS[35], // Banana
  HAND_CURATED_FOODS[23], // Paneer
  HAND_CURATED_FOODS[27], // Whole Milk
  HAND_CURATED_FOODS[29], // Plain Curd
  HAND_CURATED_FOODS[31], // Dal Tadka
  HAND_CURATED_FOODS[33]  // Whey Protein Powder
].filter(Boolean);

// Unified 11,000+ Food Database
export const ALL_CALYXO_FOODS = [
  ...HAND_CURATED_FOODS,
  ...calyxo10kFoods
];

// For backwards compatibility across all components
export const INDIAN_FOODS = ALL_CALYXO_FOODS;

/**
 * Fast search utility across all 11,000+ foods with score ranking
 * @param {string} query Search input string
 * @param {number} limit Maximum results (default: 25)
 */
export function searchCalyxoFoods(query, limit = 25) {
  if (!query || typeof query !== 'string') return [];
  const q = query.toLowerCase().trim();
  if (q.length < 1) return [];

  const tokens = q.split(/\s+/).filter(Boolean);
  const scored = [];

  for (let i = 0; i < ALL_CALYXO_FOODS.length; i++) {
    const item = ALL_CALYXO_FOODS[i];
    const nameLower = (item.name || '').toLowerCase();
    const displayLower = (item.displayName || '').toLowerCase();
    const categoryLower = (item.category || '').toLowerCase();
    const regionLower = (item.region || '').toLowerCase();
    const aliases = item.aliases || [];

    let score = 0;

    // 1. Exact name / display name match (Highest priority)
    if (nameLower === q || displayLower === q) {
      score += 1000;
    }
    // 2. Exact alias match (e.g. searching "rice" matches alias "rice")
    else if (aliases.some(a => a.toLowerCase() === q)) {
      score += 850;
    }
    // 3. Name or display name starts with query (e.g. "Rice" -> "Rice cakes")
    else if (nameLower.startsWith(q) || displayLower.startsWith(q)) {
      score += 500;
    }
    // 4. Alias starts with query
    else if (aliases.some(a => a.toLowerCase().startsWith(q))) {
      score += 400;
    }
    // 5. Individual word in name starts with query (e.g. "Steamed White Rice" contains word "Rice")
    else if (
      nameLower.split(/\s+/).some(w => w.startsWith(q)) || 
      displayLower.split(/\s+/).some(w => w.startsWith(q))
    ) {
      score += 350;
    }
    // 6. Word in alias starts with query
    else if (aliases.some(a => a.toLowerCase().split(/\s+/).some(w => w.startsWith(q)))) {
      score += 300;
    }
    // 7. Substring in name or display name
    else if (nameLower.includes(q) || displayLower.includes(q)) {
      score += 200;
    }
    // 8. Substring in alias
    else if (aliases.some(a => a.toLowerCase().includes(q))) {
      score += 150;
    }
    // 9. Match in category or region
    else if (categoryLower.includes(q) || regionLower.includes(q)) {
      score += 25;
    }

    // Token matching for multi-word queries (e.g. "chicken breast", "boiled egg", "brown rice")
    if (tokens.length > 1) {
      let allMatch = true;
      for (const t of tokens) {
        if (
          !nameLower.includes(t) && 
          !displayLower.includes(t) && 
          !categoryLower.includes(t) && 
          !regionLower.includes(t) &&
          !aliases.some(a => a.toLowerCase().includes(t))
        ) {
          allMatch = false;
          break;
        }
      }
      if (allMatch) score += 250;
    }

    // Boost verified hand-curated staple foods
    if (item.isStaple && score > 0) {
      score += 100;
    }

    if (score > 0) {
      scored.push({ item, score });
    }
  }

  return scored
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(x => x.item);
}
