// Indian Food Nutrition Dataset
// Cross-referenced with Indian Food Composition Tables (IFCT), NIN, FSSAI, and USDA databases.
// Nutrition data is stored per 100g.

export const INDIAN_FOODS = [
  // ================= NORTH INDIAN =================
  {
    name: "Roti",
    category: "North Indian",
    servingSize: "100g (approx. 3-4 small rotis)",
    calories: 264,
    protein: 8.5,
    carbs: 52.0,
    fat: 2.5,
    fiber: 6.5,
    sugar: 0.5,
    sodium: 5,
    aliases: ["roti", "phulka", "chapati", "chapathi", "rotli", "wheat flatbread", "fulka"]
  },
  {
    name: "Chapati",
    category: "North Indian",
    servingSize: "100g (approx. 3 medium chapatis)",
    calories: 264,
    protein: 8.5,
    carbs: 52.0,
    fat: 2.5,
    fiber: 6.5,
    sugar: 0.5,
    sodium: 120, // usually contains a pinch of salt
    aliases: ["chapati", "chapathi", "roti", "flatbread", "chappati"]
  },
  {
    name: "Phulka",
    category: "North Indian",
    servingSize: "100g (approx. 4 light rotis)",
    calories: 260,
    protein: 8.2,
    carbs: 53.0,
    fat: 1.5,
    fiber: 6.8,
    sugar: 0.4,
    sodium: 5,
    aliases: ["phulka", "fulka", "roti"]
  },
  {
    name: "Naan",
    category: "North Indian",
    servingSize: "100g (approx. 1 large naan)",
    calories: 290,
    protein: 8.0,
    carbs: 50.0,
    fat: 6.0,
    fiber: 2.2,
    sugar: 2.5,
    sodium: 420,
    aliases: ["naan", "nan", "butter naan", "garlic naan", "maida roti"]
  },
  {
    name: "Kulcha",
    category: "North Indian",
    servingSize: "100g (approx. 1 piece)",
    calories: 275,
    protein: 7.5,
    carbs: 51.0,
    fat: 4.5,
    fiber: 2.0,
    sugar: 2.0,
    sodium: 380,
    aliases: ["kulcha", "amritsari kulcha", "paneer kulcha"]
  },
  {
    name: "Paratha",
    category: "North Indian",
    servingSize: "100g (approx. 1.5 plain parathas)",
    calories: 326,
    protein: 6.5,
    carbs: 48.0,
    fat: 12.0,
    fiber: 3.8,
    sugar: 0.8,
    sodium: 280,
    aliases: ["paratha", "parantha", "parotta", "plain paratha", "laccha paratha"]
  },
  {
    name: "Aloo Paratha",
    category: "North Indian",
    servingSize: "100g (approx. 1 stuffed paratha)",
    calories: 210,
    protein: 4.2,
    carbs: 32.0,
    fat: 7.2,
    fiber: 3.2,
    sugar: 1.0,
    sodium: 340,
    aliases: ["aloo paratha", "alu paratha", "potato paratha", "aloo parantha"]
  },
  {
    name: "Paneer Paratha",
    category: "North Indian",
    servingSize: "100g (approx. 0.8 stuffed paratha)",
    calories: 265,
    protein: 9.8,
    carbs: 28.0,
    fat: 12.5,
    fiber: 3.0,
    sugar: 1.2,
    sodium: 390,
    aliases: ["paneer paratha", "paneer parantha", "cottage cheese paratha"]
  },
  {
    name: "Gobi Paratha",
    category: "North Indian",
    servingSize: "100g (approx. 1 stuffed paratha)",
    calories: 195,
    protein: 4.8,
    carbs: 26.0,
    fat: 8.0,
    fiber: 3.5,
    sugar: 1.5,
    sodium: 320,
    aliases: ["gobi paratha", "gobhi paratha", "cauliflower paratha", "gobi parantha"]
  },
  {
    name: "Dal Tadka",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 110,
    protein: 5.2,
    carbs: 14.0,
    fat: 3.8,
    fiber: 4.0,
    sugar: 0.5,
    sodium: 350,
    aliases: ["dal tadka", "daal tadka", "yellow dal", "toor dal", "arhar dal", "lentils"]
  },
  {
    name: "Dal Makhani",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 140,
    protein: 4.8,
    carbs: 15.0,
    fat: 6.8,
    fiber: 4.5,
    sugar: 1.2,
    sodium: 380,
    aliases: ["dal makhani", "daal makhani", "makhani dal", "black dal", "creamy lentils"]
  },
  {
    name: "Rajma",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup kidney beans curry)",
    calories: 120,
    protein: 5.0,
    carbs: 16.0,
    fat: 4.0,
    fiber: 5.2,
    sugar: 1.5,
    sodium: 360,
    aliases: ["rajma", "rajmah", "kidney bean curry", "red kidney beans"]
  },
  {
    name: "Chole",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup chickpea curry)",
    calories: 158,
    protein: 6.2,
    carbs: 21.0,
    fat: 5.5,
    fiber: 5.8,
    sugar: 1.8,
    sodium: 420,
    aliases: ["chole", "chana masala", "choley", "channa masala", "chickpea curry"]
  },
  {
    name: "Paneer Butter Masala",
    category: "North Indian",
    servingSize: "100g",
    calories: 229,
    protein: 8.5,
    carbs: 6.8,
    fat: 18.8,
    fiber: 1.2,
    sugar: 3.5,
    sodium: 450,
    aliases: ["paneer butter masala", "pbm", "butter paneer", "paneer makhani"]
  },
  {
    name: "Shahi Paneer",
    category: "North Indian",
    servingSize: "100g",
    calories: 210,
    protein: 8.0,
    carbs: 7.5,
    fat: 16.5,
    fiber: 1.0,
    sugar: 4.2,
    sodium: 430,
    aliases: ["shahi paneer", "sayi paneer", "creamy paneer curry"]
  },
  {
    name: "Palak Paneer",
    category: "North Indian",
    servingSize: "100g",
    calories: 142,
    protein: 7.2,
    carbs: 4.5,
    fat: 10.8,
    fiber: 2.2,
    sugar: 1.1,
    sodium: 390,
    aliases: ["palak paneer", "spinach and paneer", "saag paneer"]
  },
  {
    name: "Butter Chicken",
    category: "North Indian",
    servingSize: "100g",
    calories: 225,
    protein: 12.5,
    carbs: 5.5,
    fat: 16.8,
    fiber: 0.8,
    sugar: 3.2,
    sodium: 480,
    aliases: ["butter chicken", "murgh makhani", "chicken butter masala"]
  },
  {
    name: "Tandoori Chicken",
    category: "North Indian",
    servingSize: "100g (approx. 1 small leg/thigh piece)",
    calories: 177,
    protein: 23.0,
    carbs: 2.5,
    fat: 8.2,
    fiber: 0.5,
    sugar: 0.5,
    sodium: 520,
    aliases: ["tandoori chicken", "tandoori chicken breast", "tandoori leg"]
  },
  {
    name: "Chicken Curry",
    category: "North Indian",
    servingSize: "100g",
    calories: 130,
    protein: 14.5,
    carbs: 4.2,
    fat: 6.0,
    fiber: 1.2,
    sugar: 1.0,
    sodium: 390,
    aliases: ["chicken curry", "chicken gravy", "murgh curry"]
  },
  {
    name: "Mutton Curry",
    category: "North Indian",
    servingSize: "100g",
    calories: 165,
    protein: 16.0,
    carbs: 4.5,
    fat: 9.2,
    fiber: 1.2,
    sugar: 0.8,
    sodium: 410,
    aliases: ["mutton curry", "mutton gravy", "lamb curry", "goat curry", "mutton masala"]
  },
  {
    name: "Jeera Rice",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup cooked)",
    calories: 140,
    protein: 2.6,
    carbs: 28.0,
    fat: 1.8,
    fiber: 1.0,
    sugar: 0.1,
    sodium: 120,
    aliases: ["jeera rice", "cumin rice", "zeera rice"]
  },
  {
    name: "Pulao",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup cooked)",
    calories: 145,
    protein: 3.0,
    carbs: 29.0,
    fat: 2.0,
    fiber: 1.5,
    sugar: 0.4,
    sodium: 180,
    aliases: ["pulao", "pilaf", "veg pulao", "vegetable pulao", "pulav"]
  },
  {
    name: "Veg Biryani",
    category: "North Indian",
    servingSize: "100g",
    calories: 135,
    protein: 3.2,
    carbs: 24.0,
    fat: 2.8,
    fiber: 2.2,
    sugar: 0.8,
    sodium: 290,
    aliases: ["veg biryani", "vegetable biryani", "veg biriyani", "vegetable biriyani"]
  },
  {
    name: "Chicken Biryani",
    category: "North Indian",
    servingSize: "100g",
    calories: 165,
    protein: 9.5,
    carbs: 22.0,
    fat: 4.8,
    fiber: 1.2,
    sugar: 0.5,
    sodium: 320,
    aliases: ["chicken biryani", "chicken biriyani", "murgh biryani", "chick biryani"]
  },
  {
    name: "Mutton Biryani",
    category: "North Indian",
    servingSize: "100g",
    calories: 190,
    protein: 11.2,
    carbs: 21.0,
    fat: 7.2,
    fiber: 1.2,
    sugar: 0.5,
    sodium: 340,
    aliases: ["mutton biryani", "mutton biriyani", "lamb biryani", "goat biryani"]
  },
  {
    name: "Kheer",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 125,
    protein: 3.2,
    carbs: 19.0,
    fat: 4.0,
    fiber: 0.2,
    sugar: 14.0,
    sodium: 45,
    aliases: ["kheer", "payasam", "rice pudding", "rice payasa"]
  },
  {
    name: "Lassi",
    category: "North Indian",
    servingSize: "100g (approx. 100ml)",
    calories: 85,
    protein: 2.2,
    carbs: 12.0,
    fat: 3.0,
    fiber: 0.0,
    sugar: 11.0,
    sodium: 35,
    aliases: ["lassi", "sweet lassi", "mango lassi", "lassy", "yogurt drink"]
  },
  {
    name: "Gulab Jamun",
    category: "North Indian",
    servingSize: "100g (approx. 2 pieces)",
    calories: 380,
    protein: 5.5,
    carbs: 56.0,
    fat: 15.0,
    fiber: 0.5,
    sugar: 48.0,
    sodium: 90,
    aliases: ["gulab jamun", "gulabjamun", "jamun", "sweet jamun"]
  },

  // ================= SOUTH INDIAN =================
  {
    name: "Plain Dosa",
    category: "South Indian",
    servingSize: "100g (approx. 1.5 medium dosas)",
    calories: 168,
    protein: 3.9,
    carbs: 29.0,
    fat: 3.7,
    fiber: 1.8,
    sugar: 0.2,
    sodium: 180,
    aliases: ["plain dosa", "dosa", "dosai", "dose", "sada dosa", "dosay"]
  },
  {
    name: "Masala Dosa",
    category: "South Indian",
    servingSize: "100g (approx. 1 large dosa with aloo filling)",
    calories: 205,
    protein: 4.2,
    carbs: 31.0,
    fat: 7.2,
    fiber: 2.5,
    sugar: 0.5,
    sodium: 260,
    aliases: ["masala dosa", "masala dosai", "masala dose", "aloo dosa"]
  },
  {
    name: "Rava Dosa",
    category: "South Indian",
    servingSize: "100g",
    calories: 180,
    protein: 4.5,
    carbs: 32.0,
    fat: 3.8,
    fiber: 1.5,
    sugar: 0.3,
    sodium: 210,
    aliases: ["rava dosa", "ravadosa", "semolina dosa", "rave dose"]
  },
  {
    name: "Set Dosa",
    category: "South Indian",
    servingSize: "100g (approx. 2 small fluffy dosas)",
    calories: 175,
    protein: 4.0,
    carbs: 30.0,
    fat: 4.2,
    fiber: 1.6,
    sugar: 0.2,
    sodium: 190,
    aliases: ["set dosa", "set dose", "sponge dosa", "set dosai"]
  },
  {
    name: "Neer Dosa",
    category: "South Indian",
    servingSize: "100g (approx. 3 light rice dosas)",
    calories: 140,
    protein: 2.5,
    carbs: 28.0,
    fat: 2.0,
    fiber: 0.8,
    sugar: 0.1,
    sodium: 140,
    aliases: ["neer dosa", "neer dose", "neerdosa", "water dosa", "neer dosai"]
  },
  {
    name: "Mysore Masala Dosa",
    category: "South Indian",
    servingSize: "100g",
    calories: 220,
    protein: 4.5,
    carbs: 32.0,
    fat: 8.0,
    fiber: 2.8,
    sugar: 0.6,
    sodium: 280,
    aliases: ["mysore masala dosa", "mysore dosa", "mysore masala dose", "mysore masala dosai"]
  },
  {
    name: "Idli",
    category: "South Indian",
    servingSize: "100g (approx. 2.5 medium idlis)",
    calories: 120,
    protein: 3.2,
    carbs: 25.0,
    fat: 0.6,
    fiber: 1.5,
    sugar: 0.2,
    sodium: 150,
    aliases: ["idli", "idly", "steamed rice cake", "iddly", "plain idli"]
  },
  {
    name: "Mini Idli",
    category: "South Indian",
    servingSize: "100g (approx. 10 mini idlis)",
    calories: 120,
    protein: 3.2,
    carbs: 25.0,
    fat: 0.6,
    fiber: 1.5,
    sugar: 0.2,
    sodium: 150,
    aliases: ["mini idli", "mini idly", "button idli", "ghee mini idli"]
  },
  {
    name: "Ragi Idli",
    category: "South Indian",
    servingSize: "100g (approx. 2-3 ragi idlis)",
    calories: 115,
    protein: 3.0,
    carbs: 23.0,
    fat: 1.0,
    fiber: 3.2,
    sugar: 0.1,
    sodium: 140,
    aliases: ["ragi idli", "ragi idly", "finger millet idli", "nachni idli"]
  },
  {
    name: "Vada",
    category: "South Indian",
    servingSize: "100g (approx. 2 medium vadas)",
    calories: 275,
    protein: 7.2,
    carbs: 25.0,
    fat: 16.2,
    fiber: 3.8,
    sugar: 0.3,
    sodium: 310,
    aliases: ["vada", "wada", "medu vada", "meduvada", "uddina vada", "ulundu vadai"]
  },
  {
    name: "Medu Vada",
    category: "South Indian",
    servingSize: "100g (approx. 2 medium vadas)",
    calories: 275,
    protein: 7.2,
    carbs: 25.0,
    fat: 16.2,
    fiber: 3.8,
    sugar: 0.3,
    sodium: 310,
    aliases: ["medu vada", "meduvada", "vada", "uddina vada", "ulundu vadai"]
  },
  {
    name: "Upma",
    category: "South Indian",
    servingSize: "100g (approx. 0.5 cup semolina porridge)",
    calories: 165,
    protein: 3.8,
    carbs: 26.0,
    fat: 5.0,
    fiber: 2.0,
    sugar: 1.0,
    sodium: 290,
    aliases: ["upma", "uppittu", "khara bhath", "semolina upma", "uppumavu"]
  },
  {
    name: "Pongal",
    category: "South Indian",
    servingSize: "100g (approx. 0.5 cup rice & lentil porridge)",
    calories: 185,
    protein: 4.8,
    carbs: 28.0,
    fat: 6.0,
    fiber: 2.2,
    sugar: 0.2,
    sodium: 240,
    aliases: ["pongal", "ven pongal", "khara pongal", "huggi"]
  },
  {
    name: "Lemon Rice",
    category: "South Indian",
    servingSize: "100g (approx. 0.5 cup cooked)",
    calories: 172,
    protein: 3.2,
    carbs: 31.0,
    fat: 3.8,
    fiber: 1.2,
    sugar: 0.2,
    sodium: 210,
    aliases: ["lemon rice", "chitranna", "nimmakaya pulihora"]
  },
  {
    name: "Curd Rice",
    category: "South Indian",
    servingSize: "100g",
    calories: 115,
    protein: 3.0,
    carbs: 18.0,
    fat: 3.2,
    fiber: 0.8,
    sugar: 1.5,
    sodium: 190,
    aliases: ["curd rice", "dahi chawal", "mosaranna", "thayir sadam"]
  },
  {
    name: "Tamarind Rice",
    category: "South Indian",
    servingSize: "100g",
    calories: 185,
    protein: 3.5,
    carbs: 33.0,
    fat: 4.2,
    fiber: 1.5,
    sugar: 0.4,
    sodium: 240,
    aliases: ["tamarind rice", "puliyogare", "pulihora", "puli sadam"]
  },
  {
    name: "Bisi Bele Bath",
    category: "South Indian",
    servingSize: "100g",
    calories: 150,
    protein: 4.2,
    carbs: 24.0,
    fat: 4.0,
    fiber: 2.5,
    sugar: 0.6,
    sodium: 280,
    aliases: ["bisi bele bath", "bbb", "bisibelebhath", "hot lentil rice mixture"]
  },
  {
    name: "Sambar",
    category: "South Indian",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 75,
    protein: 2.5,
    carbs: 10.0,
    fat: 2.8,
    fiber: 2.8,
    sugar: 1.5,
    sodium: 320,
    aliases: ["sambar", "sambhar", "saambar", "lentil vegetable stew"]
  },
  {
    name: "Rasam",
    category: "South Indian",
    servingSize: "100g",
    calories: 45,
    protein: 1.0,
    carbs: 6.0,
    fat: 1.8,
    fiber: 1.2,
    sugar: 0.8,
    sodium: 290,
    aliases: ["rasam", "charu", "saaru", "spiced tomato soup"]
  },
  {
    name: "Coconut Chutney",
    category: "South Indian",
    servingSize: "100g (approx. 4 tbsp)",
    calories: 260,
    protein: 2.8,
    carbs: 8.5,
    fat: 24.5,
    fiber: 4.8,
    sugar: 1.2,
    sodium: 220,
    aliases: ["coconut chutney", "nariyal chutney", "kobbari pachadi", "thengai chutney"]
  },
  {
    name: "Tomato Chutney",
    category: "South Indian",
    servingSize: "100g (approx. 4 tbsp)",
    calories: 95,
    protein: 1.8,
    carbs: 8.0,
    fat: 6.2,
    fiber: 2.0,
    sugar: 3.5,
    sodium: 240,
    aliases: ["tomato chutney", "tamatar chutney", "tomato pachadi"]
  },
  {
    name: "Peanut Chutney",
    category: "South Indian",
    servingSize: "100g",
    calories: 380,
    protein: 12.0,
    carbs: 12.0,
    fat: 32.0,
    fiber: 4.5,
    sugar: 2.5,
    sodium: 280,
    aliases: ["peanut chutney", "palli chutney", "groundnut chutney", "shenga chutney"]
  },
  {
    name: "Pesarattu",
    category: "South Indian",
    servingSize: "100g (approx. 1 medium green dosa)",
    calories: 180,
    protein: 8.5,
    carbs: 26.0,
    fat: 4.5,
    fiber: 4.2,
    sugar: 0.4,
    sodium: 210,
    aliases: ["pesarattu", "moong dal dosa", "pesarattu dosa", "green gram dosa"]
  },
  {
    name: "Appam",
    category: "South Indian",
    servingSize: "100g (approx. 2 appams)",
    calories: 130,
    protein: 2.2,
    carbs: 26.0,
    fat: 1.8,
    fiber: 0.8,
    sugar: 2.0,
    sodium: 110,
    aliases: ["appam", "aapam", "kerala appam", "rice pancake"]
  },
  {
    name: "Puttu",
    category: "South Indian",
    servingSize: "100g",
    calories: 245,
    protein: 5.2,
    carbs: 48.0,
    fat: 3.5,
    fiber: 3.0,
    sugar: 1.0,
    sodium: 120,
    aliases: ["puttu", "pittu", "steamed rice cake with coconut"]
  },
  {
    name: "Kadala Curry",
    category: "South Indian",
    servingSize: "100g",
    calories: 145,
    protein: 5.5,
    carbs: 16.0,
    fat: 6.5,
    fiber: 4.8,
    sugar: 1.5,
    sodium: 310,
    aliases: ["kadala curry", "kerala black chickpea curry", "kadala"]
  },
  {
    name: "Kerala Parotta",
    category: "South Indian",
    servingSize: "100g (approx. 1 piece)",
    calories: 340,
    protein: 7.2,
    carbs: 52.0,
    fat: 11.5,
    fiber: 2.0,
    sugar: 2.0,
    sodium: 410,
    aliases: ["kerala parotta", "malabar parotta", "parotta", "barotta"]
  },
  {
    name: "Fish Curry",
    category: "South Indian",
    servingSize: "100g",
    calories: 120,
    protein: 13.5,
    carbs: 4.0,
    fat: 5.5,
    fiber: 1.0,
    sugar: 0.8,
    sodium: 360,
    aliases: ["fish curry", "meen curry", "fish gravy", "south indian fish curry"]
  },
  {
    name: "Chicken Sukka",
    category: "South Indian",
    servingSize: "100g",
    calories: 210,
    protein: 21.0,
    carbs: 4.5,
    fat: 12.0,
    fiber: 1.8,
    sugar: 0.5,
    sodium: 420,
    aliases: ["chicken sukka", "chicken kodi sukka", "dry chicken curry", "kori sukka"]
  },

  // ================= WEST INDIAN =================
  {
    name: "Poha",
    category: "West Indian",
    servingSize: "100g (approx. 0.5 cup cooked flattened rice)",
    calories: 180,
    protein: 3.5,
    carbs: 31.0,
    fat: 4.5,
    fiber: 1.8,
    sugar: 1.2,
    sodium: 220,
    aliases: ["poha", "pohe", "flattened rice", "kanda poha", "avalakki"]
  },
  {
    name: "Misal Pav",
    category: "West Indian",
    servingSize: "100g (misal curry only, excludes pav)",
    calories: 195,
    protein: 6.2,
    carbs: 24.0,
    fat: 8.0,
    fiber: 3.8,
    sugar: 2.0,
    sodium: 380,
    aliases: ["misal pav", "misal", "missal pav", "kolhapuri misal"]
  },
  {
    name: "Pav Bhaji",
    category: "West Indian",
    servingSize: "100g (bhaji curry only, excludes pav)",
    calories: 155,
    protein: 3.2,
    carbs: 20.0,
    fat: 7.2,
    fiber: 2.8,
    sugar: 2.5,
    sodium: 390,
    aliases: ["pav bhaji", "pavbhaji", "bhaji"]
  },
  {
    name: "Vada Pav",
    category: "West Indian",
    servingSize: "100g (approx. 1 vada pav)",
    calories: 250,
    protein: 5.5,
    carbs: 35.0,
    fat: 9.8,
    fiber: 2.5,
    sugar: 2.2,
    sodium: 420,
    aliases: ["vada pav", "vadapav", "wada pav", "bombay burger"]
  },
  {
    name: "Dhokla",
    category: "West Indian",
    servingSize: "100g (approx. 2-3 small square pieces)",
    calories: 160,
    protein: 6.5,
    carbs: 24.0,
    fat: 4.2,
    fiber: 1.8,
    sugar: 3.5,
    sodium: 340,
    aliases: ["dhokla", "khaman dhokla", "khaman", "gujarati dhokla"]
  },
  {
    name: "Thepla",
    category: "West Indian",
    servingSize: "100g (approx. 3 theplas)",
    calories: 275,
    protein: 7.5,
    carbs: 44.0,
    fat: 7.8,
    fiber: 4.5,
    sugar: 1.0,
    sodium: 310,
    aliases: ["thepla", "methi thepla", "gujarati thepla"]
  },
  {
    name: "Handvo",
    category: "West Indian",
    servingSize: "100g",
    calories: 210,
    protein: 7.0,
    carbs: 29.0,
    fat: 7.5,
    fiber: 3.2,
    sugar: 2.0,
    sodium: 290,
    aliases: ["handvo", "gujarati handvo", "baked lentil cake"]
  },
  {
    name: "Sev Usal",
    category: "West Indian",
    servingSize: "100g",
    calories: 185,
    protein: 5.8,
    carbs: 25.0,
    fat: 6.8,
    fiber: 3.5,
    sugar: 1.8,
    sodium: 360,
    aliases: ["sev usal", "usal", "gujarati sev usal"]
  },

  // ================= EAST INDIAN =================
  {
    name: "Luchi",
    category: "East Indian",
    servingSize: "100g (approx. 3-4 small puffed fried breads)",
    calories: 340,
    protein: 6.5,
    carbs: 48.0,
    fat: 13.5,
    fiber: 1.8,
    sugar: 0.5,
    sodium: 240,
    aliases: ["luchi", "bengali luchi", "puri", "poori"]
  },
  {
    name: "Aloo Dum",
    category: "East Indian",
    servingSize: "100g (dum aloo style potatoes)",
    calories: 115,
    protein: 2.2,
    carbs: 16.0,
    fat: 4.8,
    fiber: 2.2,
    sugar: 1.2,
    sodium: 310,
    aliases: ["aloo dum", "dum aloo", "bengali aloo dum", "potatoes in rich gravy"]
  },
  {
    name: "Fish Curry (Bengali)",
    category: "East Indian",
    servingSize: "100g (maacher jhol)",
    calories: 125,
    protein: 14.0,
    carbs: 3.5,
    fat: 6.0,
    fiber: 1.0,
    sugar: 0.6,
    sodium: 340,
    aliases: ["fish curry", "maacher jhol", "bengali fish curry", "fish jhol"]
  },
  {
    name: "Rasgulla",
    category: "East Indian",
    servingSize: "100g (approx. 2 medium pieces with syrup squeezed out)",
    calories: 186,
    protein: 4.0,
    carbs: 38.0,
    fat: 1.8,
    fiber: 0.1,
    sugar: 36.0,
    sodium: 30,
    aliases: ["rasgulla", "rosogolla", "rasgula", "sweet cottage cheese balls"]
  },
  {
    name: "Sandesh",
    category: "East Indian",
    servingSize: "100g (approx. 3 small sandesh pieces)",
    calories: 270,
    protein: 9.0,
    carbs: 32.0,
    fat: 11.5,
    fiber: 0.2,
    sugar: 28.0,
    sodium: 40,
    aliases: ["sandesh", "shondesh", "bengali sandesh"]
  },

  // ================= SNACKS =================
  {
    name: "Samosa",
    category: "Snacks",
    servingSize: "100g (approx. 1 large samosa)",
    calories: 262,
    protein: 4.5,
    carbs: 32.0,
    fat: 13.0,
    fiber: 2.2,
    sugar: 1.5,
    sodium: 360,
    aliases: ["samosa", "singara", "somosa", "fried pastry"]
  },
  {
    name: "Kachori",
    category: "Snacks",
    servingSize: "100g (approx. 1 large kachori)",
    calories: 380,
    protein: 6.8,
    carbs: 42.0,
    fat: 20.8,
    fiber: 3.0,
    sugar: 1.8,
    sodium: 410,
    aliases: ["kachori", "khasta kachori", "pyaz kachori"]
  },
  {
    name: "Pakora",
    category: "Snacks",
    servingSize: "100g (approx. 4-5 medium fritters)",
    calories: 280,
    protein: 7.0,
    carbs: 25.0,
    fat: 16.5,
    fiber: 3.5,
    sugar: 1.2,
    sodium: 340,
    aliases: ["pakora", "pakoda", "bhajia", "fritters", "onion pakoda", "veg pakora"]
  },
  {
    name: "Bhel Puri",
    category: "Snacks",
    servingSize: "100g",
    calories: 180,
    protein: 4.2,
    carbs: 30.0,
    fat: 4.8,
    fiber: 2.8,
    sugar: 3.2,
    sodium: 380,
    aliases: ["bhel puri", "bhelpuri", "bhel", "puffed rice chaat"]
  },
  {
    name: "Pani Puri",
    category: "Snacks",
    servingSize: "100g (approx. 5-6 puris filled with water & aloo)",
    calories: 140,
    protein: 2.8,
    carbs: 24.0,
    fat: 3.5,
    fiber: 2.0,
    sugar: 2.0,
    sodium: 420,
    aliases: ["pani puri", "golgappa", "puchka", "gol gappe", "panipuri"]
  },
  {
    name: "Dahi Puri",
    category: "Snacks",
    servingSize: "100g (approx. 5 pieces)",
    calories: 185,
    protein: 4.5,
    carbs: 26.0,
    fat: 7.2,
    fiber: 2.2,
    sugar: 6.0,
    sodium: 395,
    aliases: ["dahi puri", "dahipuri", "dahi batata puri"]
  },
  {
    name: "Sev Puri",
    category: "Snacks",
    servingSize: "100g (approx. 5 pieces)",
    calories: 210,
    protein: 4.0,
    carbs: 28.0,
    fat: 9.0,
    fiber: 2.5,
    sugar: 3.0,
    sodium: 410,
    aliases: ["sev puri", "sevpuri"]
  },
  {
    name: "Chaat",
    category: "Snacks",
    servingSize: "100g",
    calories: 175,
    protein: 4.2,
    carbs: 26.0,
    fat: 6.0,
    fiber: 2.8,
    sugar: 5.5,
    sodium: 440,
    aliases: ["chaat", "papdi chaat", "aloo chaat", "samosa chaat", "dahi bhalla"]
  },

  // ================= BEVERAGES =================
  {
    name: "Buttermilk",
    category: "Beverages",
    servingSize: "100g (approx. 100ml / 0.4 glass)",
    calories: 30,
    protein: 1.5,
    carbs: 3.0,
    fat: 1.2,
    fiber: 0.0,
    sugar: 2.8,
    sodium: 180, // usually salted
    aliases: ["buttermilk", "chaas", "chhaach", "sambaram", "majjige"]
  },
  {
    name: "Filter Coffee",
    category: "Beverages",
    servingSize: "100g (approx. 100ml / 0.4 cup brewed with milk & sugar)",
    calories: 75,
    protein: 2.5,
    carbs: 10.0,
    fat: 2.8,
    fiber: 0.0,
    sugar: 9.5,
    sodium: 35,
    aliases: ["filter coffee", "kaapi", "coffee", "south indian filter coffee"]
  },
  {
    name: "Masala Chai",
    category: "Beverages",
    servingSize: "100g (approx. 100ml / 0.4 cup brewed with milk & sugar)",
    calories: 65,
    protein: 2.0,
    carbs: 9.5,
    fat: 2.2,
    fiber: 0.0,
    sugar: 9.0,
    sodium: 30,
    aliases: ["masala chai", "chai", "tea", "masala tea", "ginger tea"]
  },
  {
    name: "Tender Coconut Water",
    category: "Beverages",
    servingSize: "100g (approx. 100ml)",
    calories: 19,
    protein: 0.7,
    carbs: 3.7,
    fat: 0.2,
    fiber: 0.6,
    sugar: 2.6,
    sodium: 105,
    aliases: ["tender coconut water", "coconut water", "nariyal paani", "elaneer", "karikku"]
  }
];
