// Indian Food Nutrition Dataset
// Cross-referenced with Indian Food Composition Tables (IFCT), NIN, FSSAI, and USDA databases.
// Nutrition data is stored per 100g.

export const INDIAN_FOODS = [
  // ================= NORTH INDIAN =================
  {
    name: "Roti",
    category: "North Indian",
    servingSize: "100g (approx. 3-4 small rotis)",
    calories: 264,
    protein: 8.5,
    carbs: 52.0,
    fat: 2.5,
    fiber: 6.5,
    sugar: 0.5,
    sodium: 5,
    aliases: ["roti", "phulka", "chapati", "chapathi", "rotli", "wheat flatbread", "fulka"]
  },
  {
    name: "Chapati",
    category: "North Indian",
    servingSize: "100g (approx. 3 medium chapatis)",
    calories: 264,
    protein: 8.5,
    carbs: 52.0,
    fat: 2.5,
    fiber: 6.5,
    sugar: 0.5,
    sodium: 120, // usually contains a pinch of salt
    aliases: ["chapati", "chapathi", "roti", "flatbread", "chappati"]
  },
  {
    name: "Phulka",
    category: "North Indian",
    servingSize: "100g (approx. 4 light rotis)",
    calories: 260,
    protein: 8.2,
    carbs: 53.0,
    fat: 1.5,
    fiber: 6.8,
    sugar: 0.4,
    sodium: 5,
    aliases: ["phulka", "fulka", "roti"]
  },
  {
    name: "Naan",
    category: "North Indian",
    servingSize: "100g (approx. 1 large naan)",
    calories: 290,
    protein: 8.0,
    carbs: 50.0,
    fat: 6.0,
    fiber: 2.2,
    sugar: 2.5,
    sodium: 420,
    aliases: ["naan", "nan", "butter naan", "garlic naan", "maida roti"]
  },
  {
    name: "Kulcha",
    category: "North Indian",
    servingSize: "100g (approx. 1 piece)",
    calories: 275,
    protein: 7.5,
    carbs: 51.0,
    fat: 4.5,
    fiber: 2.0,
    sugar: 2.0,
    sodium: 380,
    aliases: ["kulcha", "amritsari kulcha", "paneer kulcha"]
  },
  {
    name: "Paratha",
    category: "North Indian",
    servingSize: "100g (approx. 1.5 plain parathas)",
    calories: 326,
    protein: 6.5,
    carbs: 48.0,
    fat: 12.0,
    fiber: 3.8,
    sugar: 0.8,
    sodium: 280,
    aliases: ["paratha", "parantha", "parotta", "plain paratha", "laccha paratha"]
  },
  {
    name: "Aloo Paratha",
    category: "North Indian",
    servingSize: "100g (approx. 1 stuffed paratha)",
    calories: 210,
    protein: 4.2,
    carbs: 32.0,
    fat: 7.2,
    fiber: 3.2,
    sugar: 1.0,
    sodium: 340,
    aliases: ["aloo paratha", "alu paratha", "potato paratha", "aloo parantha"]
  },
  {
    name: "Paneer Paratha",
    category: "North Indian",
    servingSize: "100g (approx. 0.8 stuffed paratha)",
    calories: 265,
    protein: 9.8,
    carbs: 28.0,
    fat: 12.5,
    fiber: 3.0,
    sugar: 1.2,
    sodium: 390,
    aliases: ["paneer paratha", "paneer parantha", "cottage cheese paratha"]
  },
  {
    name: "Gobi Paratha",
    category: "North Indian",
    servingSize: "100g (approx. 1 stuffed paratha)",
    calories: 195,
    protein: 4.8,
    carbs: 26.0,
    fat: 8.0,
    fiber: 3.5,
    sugar: 1.5,
    sodium: 320,
    aliases: ["gobi paratha", "gobhi paratha", "cauliflower paratha", "gobi parantha"]
  },
  {
    name: "Dal Tadka",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 110,
    protein: 5.2,
    carbs: 14.0,
    fat: 3.8,
    fiber: 4.0,
    sugar: 0.5,
    sodium: 350,
    aliases: ["dal tadka", "daal tadka", "yellow dal", "toor dal", "arhar dal", "lentils"]
  },
  {
    name: "Dal Makhani",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 140,
    protein: 4.8,
    carbs: 15.0,
    fat: 6.8,
    fiber: 4.5,
    sugar: 1.2,
    sodium: 380,
    aliases: ["dal makhani", "daal makhani", "makhani dal", "black dal", "creamy lentils"]
  },
  {
    name: "Rajma",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup kidney beans curry)",
    calories: 120,
    protein: 5.0,
    carbs: 16.0,
    fat: 4.0,
    fiber: 5.2,
    sugar: 1.5,
    sodium: 360,
    aliases: ["rajma", "rajmah", "kidney bean curry", "red kidney beans"]
  },
  {
    name: "Chole",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup chickpea curry)",
    calories: 158,
    protein: 6.2,
    carbs: 21.0,
    fat: 5.5,
    fiber: 5.8,
    sugar: 1.8,
    sodium: 420,
    aliases: ["chole", "chana masala", "choley", "channa masala", "chickpea curry"]
  },
  {
    name: "Paneer Butter Masala",
    category: "North Indian",
    servingSize: "100g",
    calories: 229,
    protein: 8.5,
    carbs: 6.8,
    fat: 18.8,
    fiber: 1.2,
    sugar: 3.5,
    sodium: 450,
    aliases: ["paneer butter masala", "pbm", "butter paneer", "paneer makhani"]
  },
  {
    name: "Shahi Paneer",
    category: "North Indian",
    servingSize: "100g",
    calories: 210,
    protein: 8.0,
    carbs: 7.5,
    fat: 16.5,
    fiber: 1.0,
    sugar: 4.2,
    sodium: 430,
    aliases: ["shahi paneer", "sayi paneer", "creamy paneer curry"]
  },
  {
    name: "Palak Paneer",
    category: "North Indian",
    servingSize: "100g",
    calories: 142,
    protein: 7.2,
    carbs: 4.5,
    fat: 10.8,
    fiber: 2.2,
    sugar: 1.1,
    sodium: 390,
    aliases: ["palak paneer", "spinach and paneer", "saag paneer"]
  },
  {
    name: "Butter Chicken",
    category: "North Indian",
    servingSize: "100g",
    calories: 225,
    protein: 12.5,
    carbs: 5.5,
    fat: 16.8,
    fiber: 0.8,
    sugar: 3.2,
    sodium: 480,
    aliases: ["butter chicken", "murgh makhani", "chicken butter masala"]
  },
  {
    name: "Tandoori Chicken",
    category: "North Indian",
    servingSize: "100g (approx. 1 small leg/thigh piece)",
    calories: 177,
    protein: 23.0,
    carbs: 2.5,
    fat: 8.2,
    fiber: 0.5,
    sugar: 0.5,
    sodium: 520,
    aliases: ["tandoori chicken", "tandoori chicken breast", "tandoori leg"]
  },
  {
    name: "Chicken Curry",
    category: "North Indian",
    servingSize: "100g",
    calories: 130,
    protein: 14.5,
    carbs: 4.2,
    fat: 6.0,
    fiber: 1.2,
    sugar: 1.0,
    sodium: 390,
    aliases: ["chicken curry", "chicken gravy", "murgh curry"]
  },
  {
    name: "Mutton Curry",
    category: "North Indian",
    servingSize: "100g",
    calories: 165,
    protein: 16.0,
    carbs: 4.5,
    fat: 9.2,
    fiber: 1.2,
    sugar: 0.8,
    sodium: 410,
    aliases: ["mutton curry", "mutton gravy", "lamb curry", "goat curry", "mutton masala"]
  },
  {
    name: "Jeera Rice",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup cooked)",
    calories: 140,
    protein: 2.6,
    carbs: 28.0,
    fat: 1.8,
    fiber: 1.0,
    sugar: 0.1,
    sodium: 120,
    aliases: ["jeera rice", "cumin rice", "zeera rice"]
  },
  {
    name: "Pulao",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup cooked)",
    calories: 145,
    protein: 3.0,
    carbs: 29.0,
    fat: 2.0,
    fiber: 1.5,
    sugar: 0.4,
    sodium: 180,
    aliases: ["pulao", "pilaf", "veg pulao", "vegetable pulao", "pulav"]
  },
  {
    name: "Veg Biryani",
    category: "North Indian",
    servingSize: "100g",
    calories: 135,
    protein: 3.2,
    carbs: 24.0,
    fat: 2.8,
    fiber: 2.2,
    sugar: 0.8,
    sodium: 290,
    aliases: ["veg biryani", "vegetable biryani", "veg biriyani", "vegetable biriyani"]
  },
  {
    name: "Chicken Biryani",
    category: "North Indian",
    servingSize: "100g",
    calories: 165,
    protein: 9.5,
    carbs: 22.0,
    fat: 4.8,
    fiber: 1.2,
    sugar: 0.5,
    sodium: 320,
    aliases: ["chicken biryani", "chicken biriyani", "murgh biryani", "chick biryani"]
  },
  {
    name: "Mutton Biryani",
    category: "North Indian",
    servingSize: "100g",
    calories: 190,
    protein: 11.2,
    carbs: 21.0,
    fat: 7.2,
    fiber: 1.2,
    sugar: 0.5,
    sodium: 340,
    aliases: ["mutton biryani", "mutton biriyani", "lamb biryani", "goat biryani"]
  },
  {
    name: "Kheer",
    category: "North Indian",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 125,
    protein: 3.2,
    carbs: 19.0,
    fat: 4.0,
    fiber: 0.2,
    sugar: 14.0,
    sodium: 45,
    aliases: ["kheer", "payasam", "rice pudding", "rice payasa"]
  },
  {
    name: "Lassi",
    category: "North Indian",
    servingSize: "100g (approx. 100ml)",
    calories: 85,
    protein: 2.2,
    carbs: 12.0,
    fat: 3.0,
    fiber: 0.0,
    sugar: 11.0,
    sodium: 35,
    aliases: ["lassi", "sweet lassi", "mango lassi", "lassy", "yogurt drink"]
  },
  {
    name: "Gulab Jamun",
    category: "North Indian",
    servingSize: "100g (approx. 2 pieces)",
    calories: 380,
    protein: 5.5,
    carbs: 56.0,
    fat: 15.0,
    fiber: 0.5,
    sugar: 48.0,
    sodium: 90,
    aliases: ["gulab jamun", "gulabjamun", "jamun", "sweet jamun"]
  },

  // ================= SOUTH INDIAN =================
  {
    name: "Plain Dosa",
    category: "South Indian",
    servingSize: "100g (approx. 1.5 medium dosas)",
    calories: 168,
    protein: 3.9,
    carbs: 29.0,
    fat: 3.7,
    fiber: 1.8,
    sugar: 0.2,
    sodium: 180,
    aliases: ["plain dosa", "dosa", "dosai", "dose", "sada dosa", "dosay"]
  },
  {
    name: "Masala Dosa",
    category: "South Indian",
    servingSize: "100g (approx. 1 large dosa with aloo filling)",
    calories: 205,
    protein: 4.2,
    carbs: 31.0,
    fat: 7.2,
    fiber: 2.5,
    sugar: 0.5,
    sodium: 260,
    aliases: ["masala dosa", "masala dosai", "masala dose", "aloo dosa"]
  },
  {
    name: "Rava Dosa",
    category: "South Indian",
    servingSize: "100g",
    calories: 180,
    protein: 4.5,
    carbs: 32.0,
    fat: 3.8,
    fiber: 1.5,
    sugar: 0.3,
    sodium: 210,
    aliases: ["rava dosa", "ravadosa", "semolina dosa", "rave dose"]
  },
  {
    name: "Set Dosa",
    category: "South Indian",
    servingSize: "100g (approx. 2 small fluffy dosas)",
    calories: 175,
    protein: 4.0,
    carbs: 30.0,
    fat: 4.2,
    fiber: 1.6,
    sugar: 0.2,
    sodium: 190,
    aliases: ["set dosa", "set dose", "sponge dosa", "set dosai"]
  },
  {
    name: "Neer Dosa",
    category: "South Indian",
    servingSize: "100g (approx. 3 light rice dosas)",
    calories: 140,
    protein: 2.5,
    carbs: 28.0,
    fat: 2.0,
    fiber: 0.8,
    sugar: 0.1,
    sodium: 140,
    aliases: ["neer dosa", "neer dose", "neerdosa", "water dosa", "neer dosai"]
  },
  {
    name: "Mysore Masala Dosa",
    category: "South Indian",
    servingSize: "100g",
    calories: 220,
    protein: 4.5,
    carbs: 32.0,
    fat: 8.0,
    fiber: 2.8,
    sugar: 0.6,
    sodium: 280,
    aliases: ["mysore masala dosa", "mysore dosa", "mysore masala dose", "mysore masala dosai"]
  },
  {
    name: "Idli",
    category: "South Indian",
    servingSize: "100g (approx. 2.5 medium idlis)",
    calories: 120,
    protein: 3.2,
    carbs: 25.0,
    fat: 0.6,
    fiber: 1.5,
    sugar: 0.2,
    sodium: 150,
    aliases: ["idli", "idly", "steamed rice cake", "iddly", "plain idli"]
  },
  {
    name: "Mini Idli",
    category: "South Indian",
    servingSize: "100g (approx. 10 mini idlis)",
    calories: 120,
    protein: 3.2,
    carbs: 25.0,
    fat: 0.6,
    fiber: 1.5,
    sugar: 0.2,
    sodium: 150,
    aliases: ["mini idli", "mini idly", "button idli", "ghee mini idli"]
  },
  {
    name: "Ragi Idli",
    category: "South Indian",
    servingSize: "100g (approx. 2-3 ragi idlis)",
    calories: 115,
    protein: 3.0,
    carbs: 23.0,
    fat: 1.0,
    fiber: 3.2,
    sugar: 0.1,
    sodium: 140,
    aliases: ["ragi idli", "ragi idly", "finger millet idli", "nachni idli"]
  },
  {
    name: "Vada",
    category: "South Indian",
    servingSize: "100g (approx. 2 medium vadas)",
    calories: 275,
    protein: 7.2,
    carbs: 25.0,
    fat: 16.2,
    fiber: 3.8,
    sugar: 0.3,
    sodium: 310,
    aliases: ["vada", "wada", "medu vada", "meduvada", "uddina vada", "ulundu vadai"]
  },
  {
    name: "Medu Vada",
    category: "South Indian",
    servingSize: "100g (approx. 2 medium vadas)",
    calories: 275,
    protein: 7.2,
    carbs: 25.0,
    fat: 16.2,
    fiber: 3.8,
    sugar: 0.3,
    sodium: 310,
    aliases: ["medu vada", "meduvada", "vada", "uddina vada", "ulundu vadai"]
  },
  {
    name: "Upma",
    category: "South Indian",
    servingSize: "100g (approx. 0.5 cup semolina porridge)",
    calories: 165,
    protein: 3.8,
    carbs: 26.0,
    fat: 5.0,
    fiber: 2.0,
    sugar: 1.0,
    sodium: 290,
    aliases: ["upma", "uppittu", "khara bhath", "semolina upma", "uppumavu"]
  },
  {
    name: "Pongal",
    category: "South Indian",
    servingSize: "100g (approx. 0.5 cup rice & lentil porridge)",
    calories: 185,
    protein: 4.8,
    carbs: 28.0,
    fat: 6.0,
    fiber: 2.2,
    sugar: 0.2,
    sodium: 240,
    aliases: ["pongal", "ven pongal", "khara pongal", "huggi"]
  },
  {
    name: "Lemon Rice",
    category: "South Indian",
    servingSize: "100g (approx. 0.5 cup cooked)",
    calories: 172,
    protein: 3.2,
    carbs: 31.0,
    fat: 3.8,
    fiber: 1.2,
    sugar: 0.2,
    sodium: 210,
    aliases: ["lemon rice", "chitranna", "nimmakaya pulihora"]
  },
  {
    name: "Curd Rice",
    category: "South Indian",
    servingSize: "100g",
    calories: 115,
    protein: 3.0,
    carbs: 18.0,
    fat: 3.2,
    fiber: 0.8,
    sugar: 1.5,
    sodium: 190,
    aliases: ["curd rice", "dahi chawal", "mosaranna", "thayir sadam"]
  },
  {
    name: "Tamarind Rice",
    category: "South Indian",
    servingSize: "100g",
    calories: 185,
    protein: 3.5,
    carbs: 33.0,
    fat: 4.2,
    fiber: 1.5,
    sugar: 0.4,
    sodium: 240,
    aliases: ["tamarind rice", "puliyogare", "pulihora", "puli sadam"]
  },
  {
    name: "Bisi Bele Bath",
    category: "South Indian",
    servingSize: "100g",
    calories: 150,
    protein: 4.2,
    carbs: 24.0,
    fat: 4.0,
    fiber: 2.5,
    sugar: 0.6,
    sodium: 280,
    aliases: ["bisi bele bath", "bbb", "bisibelebhath", "hot lentil rice mixture"]
  },
  {
    name: "Sambar",
    category: "South Indian",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 75,
    protein: 2.5,
    carbs: 10.0,
    fat: 2.8,
    fiber: 2.8,
    sugar: 1.5,
    sodium: 320,
    aliases: ["sambar", "sambhar", "saambar", "lentil vegetable stew"]
  },
  {
    name: "Rasam",
    category: "South Indian",
    servingSize: "100g",
    calories: 45,
    protein: 1.0,
    carbs: 6.0,
    fat: 1.8,
    fiber: 1.2,
    sugar: 0.8,
    sodium: 290,
    aliases: ["rasam", "charu", "saaru", "spiced tomato soup"]
  },
  {
    name: "Coconut Chutney",
    category: "South Indian",
    servingSize: "100g (approx. 4 tbsp)",
    calories: 260,
    protein: 2.8,
    carbs: 8.5,
    fat: 24.5,
    fiber: 4.8,
    sugar: 1.2,
    sodium: 220,
    aliases: ["coconut chutney", "nariyal chutney", "kobbari pachadi", "thengai chutney"]
  },
  {
    name: "Tomato Chutney",
    category: "South Indian",
    servingSize: "100g (approx. 4 tbsp)",
    calories: 95,
    protein: 1.8,
    carbs: 8.0,
    fat: 6.2,
    fiber: 2.0,
    sugar: 3.5,
    sodium: 240,
    aliases: ["tomato chutney", "tamatar chutney", "tomato pachadi"]
  },
  {
    name: "Peanut Chutney",
    category: "South Indian",
    servingSize: "100g",
    calories: 380,
    protein: 12.0,
    carbs: 12.0,
    fat: 32.0,
    fiber: 4.5,
    sugar: 2.5,
    sodium: 280,
    aliases: ["peanut chutney", "palli chutney", "groundnut chutney", "shenga chutney"]
  },
  {
    name: "Pesarattu",
    category: "South Indian",
    servingSize: "100g (approx. 1 medium green dosa)",
    calories: 180,
    protein: 8.5,
    carbs: 26.0,
    fat: 4.5,
    fiber: 4.2,
    sugar: 0.4,
    sodium: 210,
    aliases: ["pesarattu", "moong dal dosa", "pesarattu dosa", "green gram dosa"]
  },
  {
    name: "Appam",
    category: "South Indian",
    servingSize: "100g (approx. 2 appams)",
    calories: 130,
    protein: 2.2,
    carbs: 26.0,
    fat: 1.8,
    fiber: 0.8,
    sugar: 2.0,
    sodium: 110,
    aliases: ["appam", "aapam", "kerala appam", "rice pancake"]
  },
  {
    name: "Puttu",
    category: "South Indian",
    servingSize: "100g",
    calories: 245,
    protein: 5.2,
    carbs: 48.0,
    fat: 3.5,
    fiber: 3.0,
    sugar: 1.0,
    sodium: 120,
    aliases: ["puttu", "pittu", "steamed rice cake with coconut"]
  },
  {
    name: "Kadala Curry",
    category: "South Indian",
    servingSize: "100g",
    calories: 145,
    protein: 5.5,
    carbs: 16.0,
    fat: 6.5,
    fiber: 4.8,
    sugar: 1.5,
    sodium: 310,
    aliases: ["kadala curry", "kerala black chickpea curry", "kadala"]
  },
  {
    name: "Kerala Parotta",
    category: "South Indian",
    servingSize: "100g (approx. 1 piece)",
    calories: 340,
    protein: 7.2,
    carbs: 52.0,
    fat: 11.5,
    fiber: 2.0,
    sugar: 2.0,
    sodium: 410,
    aliases: ["kerala parotta", "malabar parotta", "parotta", "barotta"]
  },
  {
    name: "Fish Curry",
    category: "South Indian",
    servingSize: "100g",
    calories: 120,
    protein: 13.5,
    carbs: 4.0,
    fat: 5.5,
    fiber: 1.0,
    sugar: 0.8,
    sodium: 360,
    aliases: ["fish curry", "meen curry", "fish gravy", "south indian fish curry"]
  },
  {
    name: "Chicken Sukka",
    category: "South Indian",
    servingSize: "100g",
    calories: 210,
    protein: 21.0,
    carbs: 4.5,
    fat: 12.0,
    fiber: 1.8,
    sugar: 0.5,
    sodium: 420,
    aliases: ["chicken sukka", "chicken kodi sukka", "dry chicken curry", "kori sukka"]
  },

  // ================= WEST INDIAN =================
  {
    name: "Poha",
    category: "West Indian",
    servingSize: "100g (approx. 0.5 cup cooked flattened rice)",
    calories: 180,
    protein: 3.5,
    carbs: 31.0,
    fat: 4.5,
    fiber: 1.8,
    sugar: 1.2,
    sodium: 220,
    aliases: ["poha", "pohe", "flattened rice", "kanda poha", "avalakki"]
  },
  {
    name: "Misal Pav",
    category: "West Indian",
    servingSize: "100g (misal curry only, excludes pav)",
    calories: 195,
    protein: 6.2,
    carbs: 24.0,
    fat: 8.0,
    fiber: 3.8,
    sugar: 2.0,
    sodium: 380,
    aliases: ["misal pav", "misal", "missal pav", "kolhapuri misal"]
  },
  {
    name: "Pav Bhaji",
    category: "West Indian",
    servingSize: "100g (bhaji curry only, excludes pav)",
    calories: 155,
    protein: 3.2,
    carbs: 20.0,
    fat: 7.2,
    fiber: 2.8,
    sugar: 2.5,
    sodium: 390,
    aliases: ["pav bhaji", "pavbhaji", "bhaji"]
  },
  {
    name: "Vada Pav",
    category: "West Indian",
    servingSize: "100g (approx. 1 vada pav)",
    calories: 250,
    protein: 5.5,
    carbs: 35.0,
    fat: 9.8,
    fiber: 2.5,
    sugar: 2.2,
    sodium: 420,
    aliases: ["vada pav", "vadapav", "wada pav", "bombay burger"]
  },
  {
    name: "Dhokla",
    category: "West Indian",
    servingSize: "100g (approx. 2-3 small square pieces)",
    calories: 160,
    protein: 6.5,
    carbs: 24.0,
    fat: 4.2,
    fiber: 1.8,
    sugar: 3.5,
    sodium: 340,
    aliases: ["dhokla", "khaman dhokla", "khaman", "gujarati dhokla"]
  },
  {
    name: "Thepla",
    category: "West Indian",
    servingSize: "100g (approx. 3 theplas)",
    calories: 275,
    protein: 7.5,
    carbs: 44.0,
    fat: 7.8,
    fiber: 4.5,
    sugar: 1.0,
    sodium: 310,
    aliases: ["thepla", "methi thepla", "gujarati thepla"]
  },
  {
    name: "Handvo",
    category: "West Indian",
    servingSize: "100g",
    calories: 210,
    protein: 7.0,
    carbs: 29.0,
    fat: 7.5,
    fiber: 3.2,
    sugar: 2.0,
    sodium: 290,
    aliases: ["handvo", "gujarati handvo", "baked lentil cake"]
  },
  {
    name: "Sev Usal",
    category: "West Indian",
    servingSize: "100g",
    calories: 185,
    protein: 5.8,
    carbs: 25.0,
    fat: 6.8,
    fiber: 3.5,
    sugar: 1.8,
    sodium: 360,
    aliases: ["sev usal", "usal", "gujarati sev usal"]
  },

  // ================= EAST INDIAN =================
  {
    name: "Luchi",
    category: "East Indian",
    servingSize: "100g (approx. 3-4 small puffed fried breads)",
    calories: 340,
    protein: 6.5,
    carbs: 48.0,
    fat: 13.5,
    fiber: 1.8,
    sugar: 0.5,
    sodium: 240,
    aliases: ["luchi", "bengali luchi", "puri", "poori"]
  },
  {
    name: "Aloo Dum",
    category: "East Indian",
    servingSize: "100g (dum aloo style potatoes)",
    calories: 115,
    protein: 2.2,
    carbs: 16.0,
    fat: 4.8,
    fiber: 2.2,
    sugar: 1.2,
    sodium: 310,
    aliases: ["aloo dum", "dum aloo", "bengali aloo dum", "potatoes in rich gravy"]
  },
  {
    name: "Fish Curry (Bengali)",
    category: "East Indian",
    servingSize: "100g (maacher jhol)",
    calories: 125,
    protein: 14.0,
    carbs: 3.5,
    fat: 6.0,
    fiber: 1.0,
    sugar: 0.6,
    sodium: 340,
    aliases: ["fish curry", "maacher jhol", "bengali fish curry", "fish jhol"]
  },
  {
    name: "Rasgulla",
    category: "East Indian",
    servingSize: "100g (approx. 2 medium pieces with syrup squeezed out)",
    calories: 186,
    protein: 4.0,
    carbs: 38.0,
    fat: 1.8,
    fiber: 0.1,
    sugar: 36.0,
    sodium: 30,
    aliases: ["rasgulla", "rosogolla", "rasgula", "sweet cottage cheese balls"]
  },
  {
    name: "Sandesh",
    category: "East Indian",
    servingSize: "100g (approx. 3 small sandesh pieces)",
    calories: 270,
    protein: 9.0,
    carbs: 32.0,
    fat: 11.5,
    fiber: 0.2,
    sugar: 28.0,
    sodium: 40,
    aliases: ["sandesh", "shondesh", "bengali sandesh"]
  },

  // ================= SNACKS =================
  {
    name: "Samosa",
    category: "Snacks",
    servingSize: "100g (approx. 1 large samosa)",
    calories: 262,
    protein: 4.5,
    carbs: 32.0,
    fat: 13.0,
    fiber: 2.2,
    sugar: 1.5,
    sodium: 360,
    aliases: ["samosa", "singara", "somosa", "fried pastry"]
  },
  {
    name: "Kachori",
    category: "Snacks",
    servingSize: "100g (approx. 1 large kachori)",
    calories: 380,
    protein: 6.8,
    carbs: 42.0,
    fat: 20.8,
    fiber: 3.0,
    sugar: 1.8,
    sodium: 410,
    aliases: ["kachori", "khasta kachori", "pyaz kachori"]
  },
  {
    name: "Pakora",
    category: "Snacks",
    servingSize: "100g (approx. 4-5 medium fritters)",
    calories: 280,
    protein: 7.0,
    carbs: 25.0,
    fat: 16.5,
    fiber: 3.5,
    sugar: 1.2,
    sodium: 340,
    aliases: ["pakora", "pakoda", "bhajia", "fritters", "onion pakoda", "veg pakora"]
  },
  {
    name: "Bhel Puri",
    category: "Snacks",
    servingSize: "100g",
    calories: 180,
    protein: 4.2,
    carbs: 30.0,
    fat: 4.8,
    fiber: 2.8,
    sugar: 3.2,
    sodium: 380,
    aliases: ["bhel puri", "bhelpuri", "bhel", "puffed rice chaat"]
  },
  {
    name: "Pani Puri",
    category: "Snacks",
    servingSize: "100g (approx. 5-6 puris filled with water & aloo)",
    calories: 140,
    protein: 2.8,
    carbs: 24.0,
    fat: 3.5,
    fiber: 2.0,
    sugar: 2.0,
    sodium: 420,
    aliases: ["pani puri", "golgappa", "puchka", "gol gappe", "panipuri"]
  },
  {
    name: "Dahi Puri",
    category: "Snacks",
    servingSize: "100g (approx. 5 pieces)",
    calories: 185,
    protein: 4.5,
    carbs: 26.0,
    fat: 7.2,
    fiber: 2.2,
    sugar: 6.0,
    sodium: 395,
    aliases: ["dahi puri", "dahipuri", "dahi batata puri"]
  },
  {
    name: "Sev Puri",
    category: "Snacks",
    servingSize: "100g (approx. 5 pieces)",
    calories: 210,
    protein: 4.0,
    carbs: 28.0,
    fat: 9.0,
    fiber: 2.5,
    sugar: 3.0,
    sodium: 410,
    aliases: ["sev puri", "sevpuri"]
  },
  {
    name: "Chaat",
    category: "Snacks",
    servingSize: "100g",
    calories: 175,
    protein: 4.2,
    carbs: 26.0,
    fat: 6.0,
    fiber: 2.8,
    sugar: 5.5,
    sodium: 440,
    aliases: ["chaat", "papdi chaat", "aloo chaat", "samosa chaat", "dahi bhalla"]
  },

  // ================= BEVERAGES =================
  {
    name: "Buttermilk",
    category: "Beverages",
    servingSize: "100g (approx. 100ml / 0.4 glass)",
    calories: 30,
    protein: 1.5,
    carbs: 3.0,
    fat: 1.2,
    fiber: 0.0,
    sugar: 2.8,
    sodium: 180, // usually salted
    aliases: ["buttermilk", "chaas", "chhaach", "sambaram", "majjige"]
  },
  {
    name: "Filter Coffee",
    category: "Beverages",
    servingSize: "100g (approx. 100ml / 0.4 cup brewed with milk & sugar)",
    calories: 75,
    protein: 2.5,
    carbs: 10.0,
    fat: 2.8,
    fiber: 0.0,
    sugar: 9.5,
    sodium: 35,
    aliases: ["filter coffee", "kaapi", "coffee", "south indian filter coffee"]
  },
  {
    name: "Masala Chai",
    category: "Beverages",
    servingSize: "100g (approx. 100ml / 0.4 cup brewed with milk & sugar)",
    calories: 65,
    protein: 2.0,
    carbs: 9.5,
    fat: 2.2,
    fiber: 0.0,
    sugar: 9.0,
    sodium: 30,
    aliases: ["masala chai", "chai", "tea", "masala tea", "ginger tea"]
  },
  {
    name: "Tender Coconut Water",
    category: "Beverages",
    servingSize: "100g (approx. 100ml)",
    calories: 19,
    protein: 0.7,
    carbs: 3.7,
    fat: 0.2,
    fiber: 0.6,
    sugar: 2.6,
    sodium: 105,
    aliases: ["tender coconut water", "coconut water", "nariyal paani", "elaneer", "karikku"]
  },

  // ================= MILLETS & STAPLES =================
  {
    name: "Bajra Roti",
    category: "Millets & Staples",
    servingSize: "100g (approx. 2 flatbreads)",
    calories: 290,
    protein: 9.6,
    carbs: 60.5,
    fat: 3.5,
    fiber: 8.5,
    sugar: 0.8,
    sodium: 150,
    aliases: ["bajra roti", "pearl millet roti", "kambu roti", "sajje roti"]
  },
  {
    name: "Jowar Roti",
    category: "Millets & Staples",
    servingSize: "100g (approx. 2 flatbreads)",
    calories: 280,
    protein: 8.5,
    carbs: 62.0,
    fat: 2.2,
    fiber: 9.0,
    sugar: 0.6,
    sodium: 140,
    aliases: ["jowar roti", "sorghum roti", "jolada rotti", "jowar bhakri"]
  },
  {
    name: "Ragi Roti",
    category: "Millets & Staples",
    servingSize: "100g (approx. 2 flatbreads)",
    calories: 270,
    protein: 7.2,
    carbs: 58.0,
    fat: 2.0,
    fiber: 11.0,
    sugar: 0.5,
    sodium: 180,
    aliases: ["ragi roti", "finger millet roti", "nachni roti", "ragi rotti"]
  },
  {
    name: "Makki ki Roti",
    category: "Millets & Staples",
    servingSize: "100g (approx. 2 flatbreads)",
    calories: 285,
    protein: 6.5,
    carbs: 56.0,
    fat: 4.8,
    fiber: 7.0,
    sugar: 1.2,
    sodium: 160,
    aliases: ["makki ki roti", "maize flatbread", "corn roti", "makki roti"]
  },
  {
    name: "Tandoori Roti (Plain)",
    category: "Millets & Staples",
    servingSize: "100g (approx. 2 rotis)",
    calories: 240,
    protein: 8.0,
    carbs: 50.0,
    fat: 1.2,
    fiber: 6.0,
    sugar: 0.5,
    sodium: 220,
    aliases: ["tandoori roti", "plain tandoori roti", "clay oven roti"]
  },
  {
    name: "Tandoori Roti (Butter)",
    category: "Millets & Staples",
    servingSize: "100g (approx. 2 rotis)",
    calories: 295,
    protein: 8.0,
    carbs: 50.0,
    fat: 7.5,
    fiber: 6.0,
    sugar: 0.5,
    sodium: 240,
    aliases: ["butter tandoori roti", "tandoori roti with butter"]
  },
  {
    name: "Steamed Basmati Rice (Cooked)",
    category: "Millets & Staples",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 130,
    protein: 2.7,
    carbs: 28.0,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 5,
    aliases: ["steamed rice", "cooked basmati rice", "white rice cooked", "chawal", "boiled rice"]
  },
  {
    name: "Brown Rice (Cooked)",
    category: "Millets & Staples",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 111,
    protein: 2.6,
    carbs: 23.0,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.1,
    sodium: 5,
    aliases: ["cooked brown rice", "brown chawal", "healthy rice"]
  },
  {
    name: "Khichdi (Moong Dal & Rice)",
    category: "Millets & Staples",
    servingSize: "100g (approx. 0.5 cup cooked)",
    calories: 115,
    protein: 4.0,
    carbs: 21.0,
    fat: 1.8,
    fiber: 2.5,
    sugar: 0.3,
    sodium: 250,
    aliases: ["khichdi", "khichri", "kitchari", "dal khichdi"]
  },
  {
    name: "Dalia (Broken Wheat Porridge, Salted)",
    category: "Millets & Staples",
    servingSize: "100g (approx. 0.5 cup cooked)",
    calories: 95,
    protein: 3.2,
    carbs: 18.5,
    fat: 1.2,
    fiber: 3.0,
    sugar: 0.4,
    sodium: 210,
    aliases: ["dalia", "broken wheat upma", "godhuma rava upma", "salty dalia"]
  },
  {
    name: "Oats Upma",
    category: "Millets & Staples",
    servingSize: "100g (approx. 0.5 cup cooked)",
    calories: 120,
    protein: 4.2,
    carbs: 19.0,
    fat: 3.2,
    fiber: 3.5,
    sugar: 0.8,
    sodium: 240,
    aliases: ["oats upma", "oatmeal upma", "healthy oats upma"]
  },
  {
    name: "Cow Ghee",
    category: "Millets & Staples",
    servingSize: "100g (approx. 7 tbsp)",
    calories: 884,
    protein: 0.0,
    carbs: 0.0,
    fat: 99.5,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 2,
    aliases: ["ghee", "clarified butter", "cow ghee", "pure ghee", "neyy", "tup"]
  },
  {
    name: "Salted Butter (Amul)",
    category: "Millets & Staples",
    servingSize: "100g",
    calories: 717,
    protein: 0.8,
    carbs: 0.1,
    fat: 81.0,
    fiber: 0.0,
    sugar: 0.1,
    sodium: 650,
    aliases: ["butter", "salted butter", "amul butter", "makhan"]
  },

  // ================= SUBZIS & CURRIES =================
  {
    name: "Bhindi Masala",
    category: "Subzis & Curries",
    servingSize: "100g (cooked okra)",
    calories: 90,
    protein: 2.0,
    carbs: 9.5,
    fat: 5.2,
    fiber: 3.2,
    sugar: 1.8,
    sodium: 280,
    aliases: ["bhindi masala", "okra fry", "bhindi fry", "lady finger sabji"]
  },
  {
    name: "Aloo Gobhi",
    category: "Subzis & Curries",
    servingSize: "100g",
    calories: 105,
    protein: 2.2,
    carbs: 14.0,
    fat: 4.8,
    fiber: 2.8,
    sugar: 1.5,
    sodium: 290,
    aliases: ["aloo gobhi", "aloo gobi", "potato cauliflower curry", "gobi aloo"]
  },
  {
    name: "Baingan Bharta",
    category: "Subzis & Curries",
    servingSize: "100g",
    calories: 82,
    protein: 1.6,
    carbs: 8.2,
    fat: 5.0,
    fiber: 3.0,
    sugar: 2.8,
    sodium: 260,
    aliases: ["baingan bharta", "baingan ka bharta", "eggplant bharta", "roasted brinjal curry"]
  },
  {
    name: "Egg Curry",
    category: "Subzis & Curries",
    servingSize: "100g (gravy with egg)",
    calories: 125,
    protein: 7.8,
    carbs: 3.8,
    fat: 8.8,
    fiber: 1.0,
    sugar: 1.2,
    sodium: 320,
    aliases: ["egg curry", "anda curry", "egg gravy", "anda masala"]
  },
  {
    name: "Egg Bhurji",
    category: "Subzis & Curries",
    servingSize: "100g (approx. 2 eggs scrambled)",
    calories: 160,
    protein: 11.5,
    carbs: 3.5,
    fat: 11.2,
    fiber: 0.8,
    sugar: 1.0,
    sodium: 380,
    aliases: ["egg bhurji", "scrambled egg bhurji", "anda bhurji", "indian scrambled eggs"]
  },
  {
    name: "Paneer Bhurji",
    category: "Subzis & Curries",
    servingSize: "100g",
    calories: 195,
    protein: 12.8,
    carbs: 4.5,
    fat: 14.2,
    fiber: 1.0,
    sugar: 1.5,
    sodium: 360,
    aliases: ["paneer bhurji", "scrambled paneer", "paneer bhurjee"]
  },
  {
    name: "Chicken Masala",
    category: "Subzis & Curries",
    servingSize: "100g",
    calories: 165,
    protein: 18.5,
    carbs: 3.8,
    fat: 8.5,
    fiber: 1.2,
    sugar: 0.8,
    sodium: 390,
    aliases: ["chicken masala", "chicken gravy", "kadhai chicken", "masala chicken"]
  },
  {
    name: "Fish Fry (Tava)",
    category: "Subzis & Curries",
    servingSize: "100g",
    calories: 220,
    protein: 19.0,
    carbs: 4.5,
    fat: 14.0,
    fiber: 0.8,
    sugar: 0.2,
    sodium: 420,
    aliases: ["fish fry", "tava fish fry", "fried fish", "fish rava fry"]
  },
  {
    name: "Cabbage Poriyal / Thoran",
    category: "Subzis & Curries",
    servingSize: "100g",
    calories: 75,
    protein: 1.8,
    carbs: 7.2,
    fat: 4.5,
    fiber: 2.5,
    sugar: 2.2,
    sodium: 230,
    aliases: ["cabbage poriyal", "cabbage thoran", "cabbage dry curry", "patta gobhi sabji"]
  },
  {
    name: "Avial",
    category: "Subzis & Curries",
    servingSize: "100g",
    calories: 110,
    protein: 2.2,
    carbs: 9.8,
    fat: 7.2,
    fiber: 3.0,
    sugar: 1.8,
    sodium: 250,
    aliases: ["avial", "kerala avial", "mixed veg coconut curry"]
  },
  {
    name: "Lauki Sabzi",
    category: "Subzis & Curries",
    servingSize: "100g",
    calories: 55,
    protein: 1.0,
    carbs: 4.5,
    fat: 3.6,
    fiber: 1.8,
    sugar: 1.5,
    sodium: 210,
    aliases: ["lauki sabzi", "doodhi sabji", "bottle gourd curry", "ghia ki sabji"]
  },

  // ================= BREAKFAST & SNACKS =================
  {
    name: "Veg Momos (Steamed)",
    category: "Breakfast & Snacks",
    servingSize: "100g (approx. 4-5 pieces)",
    calories: 135,
    protein: 3.5,
    carbs: 26.0,
    fat: 1.8,
    fiber: 2.0,
    sugar: 1.5,
    sodium: 320,
    aliases: ["veg momos", "steamed veg momos", "dumplings", "vegetable momo"]
  },
  {
    name: "Chicken Momos (Steamed)",
    category: "Breakfast & Snacks",
    servingSize: "100g (approx. 4-5 pieces)",
    calories: 160,
    protein: 9.2,
    carbs: 24.0,
    fat: 3.2,
    fiber: 1.2,
    sugar: 1.0,
    sodium: 360,
    aliases: ["chicken momos", "steamed chicken momos", "chicken dumplings"]
  },
  {
    name: "Bread Pakora",
    category: "Breakfast & Snacks",
    servingSize: "100g (approx. 1 piece)",
    calories: 290,
    protein: 6.5,
    carbs: 34.0,
    fat: 14.2,
    fiber: 2.5,
    sugar: 1.8,
    sodium: 420,
    aliases: ["bread pakora", "bread pakoda", "fried bread snack"]
  },
  {
    name: "Rava Idli",
    category: "Breakfast & Snacks",
    servingSize: "100g (approx. 2 idlis)",
    calories: 155,
    protein: 4.2,
    carbs: 29.0,
    fat: 2.5,
    fiber: 1.5,
    sugar: 0.5,
    sodium: 240,
    aliases: ["rava idli", "semolina idly", "sooji idli"]
  },
  {
    name: "Sabudana Khichdi",
    category: "Breakfast & Snacks",
    servingSize: "100g",
    calories: 250,
    protein: 2.5,
    carbs: 45.0,
    fat: 6.8,
    fiber: 1.5,
    sugar: 1.0,
    sodium: 280,
    aliases: ["sabudana khichdi", "sago pilaf", "sabudana khichri"]
  },
  {
    name: "Omelette (Double Egg)",
    category: "Breakfast & Snacks",
    servingSize: "100g (approx. 1 large omelette with onions & chillies)",
    calories: 175,
    protein: 12.0,
    carbs: 2.5,
    fat: 13.0,
    fiber: 0.5,
    sugar: 0.5,
    sodium: 350,
    aliases: ["omelette", "double egg omelette", "omelet", "egg omelette"]
  },
  {
    name: "Plain Pav",
    category: "Breakfast & Snacks",
    servingSize: "100g (approx. 2 pav buns)",
    calories: 270,
    protein: 8.2,
    carbs: 54.0,
    fat: 2.2,
    fiber: 2.0,
    sugar: 4.0,
    sodium: 480,
    aliases: ["pav", "plain pav", "laadi pav", "bread roll"]
  },
  {
    name: "Toast Butter (2 slices)",
    category: "Breakfast & Snacks",
    servingSize: "100g (approx. 2 slices of white bread with butter)",
    calories: 320,
    protein: 7.0,
    carbs: 48.0,
    fat: 11.5,
    fiber: 2.2,
    sugar: 3.5,
    sodium: 490,
    aliases: ["toast butter", "bread butter", "butter toast"]
  },
  {
    name: "Masala Vadai (Chana Dal Vada)",
    category: "Breakfast & Snacks",
    servingSize: "100g (approx. 3 small vadas)",
    calories: 310,
    protein: 9.8,
    carbs: 32.0,
    fat: 16.0,
    fiber: 6.5,
    sugar: 0.5,
    sodium: 340,
    aliases: ["masala vadai", "masala vada", "paruppu vadai", "chana dal vada"]
  },

  // ================= SWEETS & DESSERTS =================
  {
    name: "Jalebi",
    category: "Sweets & Desserts",
    servingSize: "100g (approx. 3-4 pieces)",
    calories: 395,
    protein: 2.2,
    carbs: 78.0,
    fat: 8.5,
    fiber: 0.5,
    sugar: 65.0,
    sodium: 120,
    aliases: ["jalebi", "jalibi", "sweet spiral"]
  },
  {
    name: "Gajar ka Halwa",
    category: "Sweets & Desserts",
    servingSize: "100g",
    calories: 220,
    protein: 4.2,
    carbs: 32.0,
    fat: 8.5,
    fiber: 1.8,
    sugar: 26.0,
    sodium: 60,
    aliases: ["gajar ka halwa", "gajar halwa", "carrot halwa", "carrot pudding"]
  },
  {
    name: "Mysore Pak",
    category: "Sweets & Desserts",
    servingSize: "100g",
    calories: 540,
    protein: 4.8,
    carbs: 52.0,
    fat: 35.0,
    fiber: 1.2,
    sugar: 45.0,
    sodium: 40,
    aliases: ["mysore pak", "mysurpa", "ghee mysore pak"]
  },
  {
    name: "Rasmalai",
    category: "Sweets & Desserts",
    servingSize: "100g (approx. 2 pieces with milk liquid)",
    calories: 250,
    protein: 7.2,
    carbs: 28.0,
    fat: 12.0,
    fiber: 0.2,
    sugar: 24.0,
    sodium: 80,
    aliases: ["rasmalai", "rossomalai", "sweet milk dessert"]
  },
  {
    name: "Besan Laddu",
    category: "Sweets & Desserts",
    servingSize: "100g (approx. 3 pieces)",
    calories: 470,
    protein: 8.5,
    carbs: 56.0,
    fat: 23.5,
    fiber: 2.8,
    sugar: 38.0,
    sodium: 45,
    aliases: ["besan laddu", "besan ladoo", "gram flour sweet ball"]
  },

  // ================= BEVERAGES (ADDITIONAL) =================
  {
    name: "Black Tea (No Sugar)",
    category: "Beverages",
    servingSize: "100g (approx. 100ml / 0.4 cup brewed)",
    calories: 2,
    protein: 0.1,
    carbs: 0.3,
    fat: 0.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 3,
    aliases: ["black tea", "tea no sugar", "sulaimani tea", "lal cha"]
  },
  {
    name: "Green Tea (No Sugar)",
    category: "Beverages",
    servingSize: "100g (approx. 100ml)",
    calories: 1,
    protein: 0.0,
    carbs: 0.2,
    fat: 0.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 2,
    aliases: ["green tea", "green tea no sugar", "herbal tea"]
  },
  {
    name: "Black Coffee (No Sugar)",
    category: "Beverages",
    servingSize: "100g (approx. 100ml)",
    calories: 2,
    protein: 0.2,
    carbs: 0.3,
    fat: 0.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 2,
    aliases: ["black coffee", "espresso", "americano", "coffee no sugar"]
  },
  {
    name: "Nimbu Pani (Lemonade with Sugar)",
    category: "Beverages",
    servingSize: "100g (approx. 100ml)",
    calories: 42,
    protein: 0.2,
    carbs: 10.5,
    fat: 0.1,
    fiber: 0.2,
    sugar: 9.8,
    sodium: 80,
    aliases: ["nimbu pani", "shikanji", "lemonade", "sweet lemon water"]
  },
  {
    name: "Nimbu Pani (Salted / No Sugar)",
    category: "Beverages",
    servingSize: "100g (approx. 100ml)",
    calories: 4,
    protein: 0.1,
    carbs: 1.0,
    fat: 0.0,
    fiber: 0.2,
    sugar: 0.2,
    sodium: 120,
    aliases: ["salted lemon water", "nimbu pani sugar free", "sugarfree shikanji"]
  },
  {
    name: "Sweet Lime Juice (Mosambi)",
    category: "Beverages",
    servingSize: "100g (approx. 100ml fresh juice)",
    calories: 45,
    protein: 0.7,
    carbs: 10.5,
    fat: 0.1,
    fiber: 0.4,
    sugar: 8.5,
    sodium: 5,
    aliases: ["sweet lime juice", "mosambi juice", "fresh mosambi juice"]
  },
  {
    name: "Orange Juice (Fresh)",
    category: "Beverages",
    servingSize: "100g (approx. 100ml)",
    calories: 47,
    protein: 0.9,
    carbs: 11.0,
    fat: 0.2,
    fiber: 0.2,
    sugar: 9.0,
    sodium: 2,
    aliases: ["orange juice", "santra juice", "fresh orange juice"]
  },
  {
    name: "Badam Milk",
    category: "Beverages",
    servingSize: "100g (approx. 100ml sweet almond milk drink)",
    calories: 110,
    protein: 3.5,
    carbs: 14.0,
    fat: 4.5,
    fiber: 0.5,
    sugar: 12.0,
    sodium: 40,
    aliases: ["badam milk", "almond milk drink", "sweet badam milk"]
  },
  {
    name: "Sugarcane Juice",
    category: "Beverages",
    servingSize: "100g (approx. 100ml)",
    calories: 80,
    protein: 0.3,
    carbs: 20.0,
    fat: 0.1,
    fiber: 0.5,
    sugar: 19.0,
    sodium: 10,
    aliases: ["sugarcane juice", "ganne ka ras", "fresh sugarcane juice"]
  },

  // ================= DAIRY & EGGS =================
  {
    name: "Paneer (Raw, Full Cream)",
    category: "Dairy & Eggs",
    servingSize: "100g",
    calories: 320,
    protein: 18.0,
    carbs: 3.5,
    fat: 26.0,
    fiber: 0.0,
    sugar: 2.8,
    sodium: 30,
    aliases: ["paneer raw", "full cream paneer", "cottage cheese raw", "paneer"]
  },
  {
    name: "Paneer (Raw, Low Fat)",
    category: "Dairy & Eggs",
    servingSize: "100g",
    calories: 190,
    protein: 21.0,
    carbs: 4.0,
    fat: 10.0,
    fiber: 0.0,
    sugar: 3.0,
    sodium: 35,
    aliases: ["low fat paneer", "raw low fat paneer", "slim paneer"]
  },
  {
    name: "Tofu (Raw)",
    category: "Dairy & Eggs",
    servingSize: "100g",
    calories: 76,
    protein: 8.0,
    carbs: 1.9,
    fat: 4.8,
    fiber: 0.3,
    sugar: 0.5,
    sodium: 7,
    aliases: ["tofu", "raw tofu", "soya paneer", "soy bean curd"]
  },
  {
    name: "Egg White (Boiled)",
    category: "Dairy & Eggs",
    servingSize: "100g (approx. 3 egg whites)",
    calories: 52,
    protein: 11.0,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0.0,
    sugar: 0.7,
    sodium: 166,
    aliases: ["boiled egg white", "egg white only", "eggwhite"]
  },
  {
    name: "Whole Egg (Boiled)",
    category: "Dairy & Eggs",
    servingSize: "100g (approx. 2 eggs)",
    calories: 155,
    protein: 12.6,
    carbs: 1.1,
    fat: 10.6,
    fiber: 0.0,
    sugar: 1.1,
    sodium: 124,
    aliases: ["boiled egg", "boiled whole egg", "egg boiled"]
  },
  {
    name: "Curd (Whole Milk)",
    category: "Dairy & Eggs",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0.0,
    sugar: 4.7,
    sodium: 46,
    aliases: ["curd", "dahi", "yogurt", "plain curd", "perugu", "thayir"]
  },
  {
    name: "Curd (Skimmed Milk / Low Fat)",
    category: "Dairy & Eggs",
    servingSize: "100g (approx. 0.5 cup)",
    calories: 43,
    protein: 3.8,
    carbs: 5.0,
    fat: 0.8,
    fiber: 0.0,
    sugar: 5.0,
    sodium: 50,
    aliases: ["low fat curd", "skimmed curd", "low fat dahi", "slimming dahi"]
  },
  {
    name: "Cow Milk (Whole)",
    category: "Dairy & Eggs",
    servingSize: "100g (approx. 100ml)",
    calories: 62,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.5,
    fiber: 0.0,
    sugar: 4.8,
    sodium: 44,
    aliases: ["cow milk", "milk", "full cream cow milk"]
  },
  {
    name: "Cow Milk (Toned / Low Fat)",
    category: "Dairy & Eggs",
    servingSize: "100g (approx. 100ml)",
    calories: 47,
    protein: 3.1,
    carbs: 4.8,
    fat: 1.6,
    fiber: 0.0,
    sugar: 4.8,
    sodium: 48,
    aliases: ["toned milk", "low fat milk", "cow milk toned", "diet milk"]
  },
  {
    name: "Buffalo Milk (Whole)",
    category: "Dairy & Eggs",
    servingSize: "100g (approx. 100ml)",
    calories: 97,
    protein: 3.8,
    carbs: 5.2,
    fat: 6.8,
    fiber: 0.0,
    sugar: 5.2,
    sodium: 52,
    aliases: ["buffalo milk", "whole buffalo milk", "creamy milk"]
  }
];
